"""Minimal Excalidraw-to-PNG renderer.

Reads a .excalidraw JSON file and rasterises rectangles, text, and arrows
using Pillow. Designed for the diagrams generated by *.gen.py in this dir —
not a general Excalidraw renderer (no freedraw, no images, no rough.js).

Run: python3 render_excalidraw.py <input.excalidraw> [output.png]
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

# 2x supersample for crisper rasterization
SCALE = 2

# Try a few fonts in order — first one with broad Unicode coverage wins.
# Arial Unicode MS covers em-dash, ∈, ✗, subscripts ₁₂₃, Greek (α, Δ), etc.
_FONT_CANDIDATES = [
    "/Library/Fonts/Arial Unicode.ttf",
    "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
    "/System/Library/Fonts/Apple Symbols.ttf",
    "/System/Library/Fonts/Supplemental/Verdana.ttf",
    "/System/Library/Fonts/Supplemental/Arial.ttf",
    "/System/Library/Fonts/Helvetica.ttc",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
]

# Glyph substitutions (Verdana etc. don't ship colour emoji).
_SUBS = {
    "❌": "✗",
    "ℝ": "R",
}

def _sub(s: str) -> str:
    for a, b in _SUBS.items():
        s = s.replace(a, b)
    return s

def _font(size: int):
    for path in _FONT_CANDIDATES:
        if Path(path).exists():
            try:
                return ImageFont.truetype(path, size=size * SCALE)
            except OSError:
                continue
    return ImageFont.load_default()

def _draw_dashed_rect(draw: ImageDraw.ImageDraw, xy, outline, width, dash=14, gap=8):
    x1, y1, x2, y2 = xy
    edges = [
        ((x1, y1), (x2, y1)),  # top
        ((x2, y1), (x2, y2)),  # right
        ((x2, y2), (x1, y2)),  # bottom
        ((x1, y2), (x1, y1)),  # left
    ]
    d = dash * SCALE
    g = gap * SCALE
    for (sx, sy), (ex, ey) in edges:
        dx, dy = ex - sx, ey - sy
        length = math.hypot(dx, dy)
        if length == 0: continue
        ux, uy = dx / length, dy / length
        pos = 0.0
        while pos < length:
            seg_end = min(pos + d, length)
            draw.line(
                [(sx + ux * pos, sy + uy * pos),
                 (sx + ux * seg_end, sy + uy * seg_end)],
                fill=outline, width=width,
            )
            pos = seg_end + g

def _measure_lines(font, lines: list[str]) -> tuple[int, int, list[int]]:
    """Return (total_w, total_h, per_line_widths). Uses font.getbbox."""
    widths = []
    heights = []
    for ln in lines:
        bb = font.getbbox(ln)
        widths.append(bb[2] - bb[0])
        heights.append(bb[3] - bb[1])
    total_w = max(widths) if widths else 0
    line_h = max(heights) if heights else font.size
    total_h = line_h * len(lines) + int(line_h * 0.25) * (len(lines) - 1)
    return total_w, total_h, widths

def render(input_path: Path, output_path: Path) -> None:
    doc = json.loads(input_path.read_text())
    elements = doc.get("elements", [])

    # Compute bounding box (excalidraw uses top-left origin; we add 40px padding)
    pad = 40
    max_x = max(e["x"] + e.get("width", 0) for e in elements)
    max_y = max(e["y"] + e.get("height", 0) for e in elements)
    W = (int(max_x) + pad) * SCALE
    H = (int(max_y) + pad) * SCALE

    bg = doc.get("appState", {}).get("viewBackgroundColor", "#ffffff")
    img = Image.new("RGB", (W, H), bg)
    draw = ImageDraw.Draw(img)

    # Pass 1: rectangles + arrows
    for e in elements:
        t = e["type"]
        if t == "rectangle":
            x = e["x"] * SCALE
            y = e["y"] * SCALE
            w = e["width"] * SCALE
            h = e["height"] * SCALE
            stroke = e["strokeColor"]
            fill   = e["backgroundColor"]
            sw     = int(e.get("strokeWidth", 2)) * SCALE
            radius = 8 * SCALE if e.get("roundness") else 0
            if fill and fill != "transparent":
                draw.rounded_rectangle((x, y, x + w, y + h), radius=radius, fill=fill)
            if e.get("strokeStyle") == "dashed":
                _draw_dashed_rect(draw, (x, y, x + w, y + h),
                                  outline=stroke, width=sw)
            else:
                draw.rounded_rectangle((x, y, x + w, y + h),
                                       radius=radius, outline=stroke, width=sw)
        elif t == "arrow":
            x0 = e["x"] * SCALE
            y0 = e["y"] * SCALE
            (px0, py0), (px1, py1) = e["points"][0], e["points"][-1]
            sx, sy = x0 + px0 * SCALE, y0 + py0 * SCALE
            ex, ey = x0 + px1 * SCALE, y0 + py1 * SCALE
            stroke = e["strokeColor"]
            sw     = int(e.get("strokeWidth", 2)) * SCALE
            draw.line([(sx, sy), (ex, ey)], fill=stroke, width=sw)
            if e.get("endArrowhead") == "arrow":
                # 12px triangle, pointing in (ex-sx, ey-sy) direction
                ah = 12 * SCALE
                ang = math.atan2(ey - sy, ex - sx)
                spread = math.radians(22)
                p1 = (ex - ah * math.cos(ang - spread),
                      ey - ah * math.sin(ang - spread))
                p2 = (ex - ah * math.cos(ang + spread),
                      ey - ah * math.sin(ang + spread))
                draw.polygon([(ex, ey), p1, p2], fill=stroke)

    # Pass 2: text (drawn on top of boxes)
    for e in elements:
        if e["type"] != "text":
            continue
        size = int(e.get("fontSize", 16))
        font = _font(size)
        color = e.get("strokeColor", "#000000")
        x = e["x"] * SCALE
        y = e["y"] * SCALE
        w = e["width"] * SCALE
        h = e["height"] * SCALE
        lines = _sub(e["text"]).split("\n")
        tw, th, line_widths = _measure_lines(font, lines)

        # vertical alignment
        valign = e.get("verticalAlign", "top")
        if valign == "middle":
            ty = y + (h - th) / 2
        elif valign == "bottom":
            ty = y + (h - th)
        else:
            ty = y

        # per-line horizontal alignment
        halign = e.get("textAlign", "left")
        line_h = th / max(len(lines), 1)
        for ln, lw in zip(lines, line_widths):
            if halign == "center":
                tx = x + (w - lw) / 2
            elif halign == "right":
                tx = x + (w - lw)
            else:
                tx = x
            draw.text((tx, ty), ln, fill=color, font=font)
            ty += line_h * 1.0  # _measure_lines already factors line spacing into total

    # Downsample to final size
    final_w = W // SCALE
    final_h = H // SCALE
    img = img.resize((final_w, final_h), Image.Resampling.LANCZOS)
    img.save(output_path, "PNG", optimize=True)
    print(f"wrote {output_path}  ({final_w} x {final_h}, {output_path.stat().st_size} bytes)")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("usage: render_excalidraw.py <input.excalidraw> [output.png]", file=sys.stderr)
        sys.exit(2)
    inp = Path(sys.argv[1])
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else inp.with_suffix(".png")
    render(inp, out)
