# DongTing Syscall Anomaly Detection
### Isolation Forest + Variational Autoencoder — 174-dim Feature Engineering

> G. Duan et al., *DongTing: A large-scale dataset for anomaly detection of the Linux kernel*, JSS 2023.

**Dataset:** 18,966 labeled syscall sequences (6,850 normal + 12,116 attack), pre-split 80/10/10.
**Goal:** Detect attack sequences using **unsupervised** methods trained only on normal sequences.
**Methods:** Isolation Forest · Variational Autoencoder · Ensemble (α=0.7·VAE + 0.3·IF)
**Feature groups:** freq_60 · disc_40 · stats_8 · bigram_40 · ver_onehot → **174 dims**


## 1. Setup & Imports

In [1]:
import os, json, warnings, collections
import numpy as np
import pandas as pd
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import entropy as scipy_entropy
warnings.filterwarnings('ignore')

from pymongo import MongoClient
from tqdm import tqdm

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import (
    roc_auc_score, average_precision_score, roc_curve,
    classification_report, confusion_matrix, f1_score,
    precision_score, recall_score, accuracy_score
)
from sklearn.feature_selection import mutual_info_classif

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

np.random.seed(42)
tf.random.set_seed(42)

MONGO_URI = os.environ.get('MONGO_URI', 'mongodb://mongo:27017/')
MONGO_DB  = os.environ.get('MONGO_DB',  'syzbot_DB')
OUT = 'outputs'; os.makedirs(OUT, exist_ok=True)

print(f'TensorFlow: {tf.__version__}')
print(f'NumPy: {np.__version__}')


TensorFlow: 2.21.0
NumPy: 2.4.4


## 2. Load Data from MongoDB

### Collections
| Collection | Content |
|---|---|
| `kernel_convert_baseline` | Labels + train/val/test split for all 18,966 sequences |
| `kernel_syscall_normal_strace` | Normal sequences — `kns_normal_mlseq_list` (pipe-sep IDs) |
| `kernel_syscallhook_bugpoc_trace_sum` | Attack sequences — `kshs_bugpoc_syscall_list` (pipe-sep syscall names) |

**Join keys (verified):**
- Normal: `baseline.kcb_bug_name` == `normal_strace.kns_normal_file_name` (100% overlap, do NOT strip `.log`)
- Attack: `baseline.kcb_bug_name` == `attack_strace.kshs_poclog_name` (100% overlap)


In [2]:
client = MongoClient(MONGO_URI)
db = client[MONGO_DB]

# Verify collection sizes
for col in ['kernel_convert_baseline','kernel_syscall_normal_strace',
            'kernel_syscallhook_bugpoc_trace_sum']:
    n = db[col].estimated_document_count()
    print(f'{col}: {n:,} docs')


kernel_convert_baseline: 18,966 docs
kernel_syscall_normal_strace: 6,850 docs
kernel_syscallhook_bugpoc_trace_sum: 12,116 docs


In [3]:
# Load syscall name→ID lookup from syscall_64.tbl
syscall_tbl      = {}  # id   → name
syscall_name_to_id = {}  # name → id
with open('/workspace/data/dongting/syscall_64.tbl') as f:
    for line in f:
        parts = line.strip().split()
        if parts and parts[0].isdigit():
            sid, sname = int(parts[0]), parts[2]
            syscall_tbl[sid] = sname
            syscall_name_to_id[sname] = sid
print(f'Syscall table: {len(syscall_tbl)} entries (IDs {min(syscall_tbl)} – {max(syscall_tbl)})')

def id_to_name(sid):
    return syscall_tbl.get(sid, str(sid))


Syscall table: 398 entries (IDs 0 – 547)


In [4]:
def to_int(v):
    try: return int(v)
    except: return 0

def parse_ml(s):
    """Parse pipe-separated numeric syscall IDs (normal sequences)."""
    if not s or not isinstance(s, str) or s.startswith(('sy_', 'ml_')):
        return []
    return [int(x) for x in s.split('|') if x.strip().lstrip('-').isdigit()]

def parse_names(s):
    """Parse pipe-separated syscall names → IDs (attack sequences)."""
    if not s or not isinstance(s, str):
        return []
    return [syscall_name_to_id[n.strip()] for n in s.split('|')
            if n.strip() in syscall_name_to_id]

# ── Baseline metadata ─────────────────────────────────────────────────────────
print('Loading baseline metadata...')
docs = list(db['kernel_convert_baseline'].find({}, {'_id': 0}))
df = pd.DataFrame(docs)
df['syscall_counts'] = df['kcb_syscall_counts'].apply(to_int)
df['syscall_sizes']  = df['kcb_syscall_sizes'].apply(to_int)
df['label']      = (df['kcb_seq_lables'] == 'Attach').astype(int)
df['label_name'] = df['label'].map({0: 'Normal', 1: 'Attack'})
df['split']      = df['kcb_seq_class'].map({
    'DTDS-train': 'train', 'DTDS-validation': 'val', 'DTDS-test': 'test'
})
print(f'Baseline: {len(df)} sequences')
print(df.groupby(['label_name', 'split']).size().unstack(fill_value=0))


Loading baseline metadata...
Baseline: 18966 sequences
split       test  train   val
label_name                   
Attack      1633   9356  1127
Normal       678   5487   685


In [5]:
# ── Load full sequences into memory ───────────────────────────────────────────
print('Loading normal sequences (mlseq IDs)...')
normal_seqs = {}   # filename → list[int]
for doc in tqdm(db['kernel_syscall_normal_strace'].find(
        {}, {'kns_normal_file_name': 1, 'kns_normal_mlseq_list': 1}), total=6850):
    normal_seqs[doc['kns_normal_file_name']] = parse_ml(doc.get('kns_normal_mlseq_list', ''))

print('Loading attack sequences (syscall names → IDs)...')
attack_seqs = {}   # poclog_name → list[int]
for doc in tqdm(db['kernel_syscallhook_bugpoc_trace_sum'].find(
        {}, {'kshs_poclog_name': 1, 'kshs_bugpoc_syscall_list': 1}), total=12116):
    attack_seqs[doc['kshs_poclog_name']] = parse_names(doc.get('kshs_bugpoc_syscall_list', ''))

def get_seq(row):
    if row['label'] == 0:
        return normal_seqs.get(row['kcb_bug_name'], [])   # key includes .log extension
    else:
        return attack_seqs.get(row['kcb_bug_name'], [])

print('Joining sequences to metadata...')
df['seq']     = [get_seq(r) for _, r in tqdm(df.iterrows(), total=len(df))]
df['seq_len'] = df['seq'].apply(len)
df['n_unique']= df['seq'].apply(lambda s: len(set(s)))

filled = (df.seq_len > 0).sum()
print(f'Sequences with content: {filled} / {len(df)}  ({100*filled/len(df):.1f}%)')


Loading normal sequences (mlseq IDs)...


  0%|          | 0/6850 [00:00<?, ?it/s]

 17%|█▋        | 1164/6850 [00:00<00:00, 7602.42it/s]

 28%|██▊       | 1925/6850 [00:00<00:01, 2873.76it/s]

 34%|███▍      | 2340/6850 [00:01<00:04, 1008.51it/s]

 38%|███▊      | 2583/6850 [00:01<00:04, 1008.22it/s]

 40%|████      | 2770/6850 [00:02<00:04, 897.09it/s] 

 44%|████▎     | 2980/6850 [00:02<00:03, 974.42it/s]

 46%|████▌     | 3121/6850 [00:02<00:04, 779.56it/s]

 47%|████▋     | 3229/6850 [00:02<00:04, 729.47it/s]

 48%|████▊     | 3320/6850 [00:03<00:06, 560.91it/s]

 50%|████▉     | 3391/6850 [00:03<00:07, 445.21it/s]

 50%|█████     | 3446/6850 [00:03<00:08, 419.77it/s]

 52%|█████▏    | 3531/6850 [00:03<00:07, 465.73it/s]

 53%|█████▎    | 3644/6850 [00:04<00:05, 566.93it/s]

 54%|█████▍    | 3716/6850 [00:04<00:05, 550.03it/s]

 57%|█████▋    | 3921/6850 [00:04<00:03, 829.18it/s]

 59%|█████▊    | 4024/6850 [00:04<00:04, 570.29it/s]

 60%|██████    | 4140/6850 [00:04<00:04, 668.59it/s]

 67%|██████▋   | 4616/6850 [00:04<00:01, 1445.77it/s]

 87%|████████▋ | 5929/6850 [00:05<00:00, 2711.94it/s]

 90%|█████████ | 6196/6850 [00:05<00:00, 2303.14it/s]

 94%|█████████▍| 6423/6850 [00:05<00:00, 1598.26it/s]

100%|██████████| 6850/6850 [00:05<00:00, 1820.06it/s]

100%|██████████| 6850/6850 [00:05<00:00, 1157.41it/s]

Loading attack sequences (syscall names → IDs)...


  0%|          | 0/12116 [00:00<?, ?it/s]

  1%|          | 102/12116 [00:00<00:16, 749.76it/s]

  3%|▎         | 346/12116 [00:00<00:07, 1613.97it/s]

  4%|▍         | 541/12116 [00:00<00:07, 1474.96it/s]

  8%|▊         | 990/12116 [00:00<00:04, 2405.54it/s]

 10%|█         | 1246/12116 [00:00<00:07, 1463.91it/s]

 12%|█▏        | 1439/12116 [00:00<00:07, 1348.80it/s]

 15%|█▌        | 1849/12116 [00:01<00:05, 1913.41it/s]

 17%|█▋        | 2092/12116 [00:01<00:09, 1067.43it/s]

 20%|█▉        | 2370/12116 [00:01<00:07, 1316.90it/s]

 21%|██▏       | 2581/12116 [00:01<00:07, 1352.36it/s]

 23%|██▎       | 2773/12116 [00:01<00:06, 1455.61it/s]

 24%|██▍       | 2964/12116 [00:02<00:06, 1495.54it/s]

 27%|██▋       | 3281/12116 [00:02<00:05, 1617.99it/s]

 29%|██▊       | 3465/12116 [00:02<00:05, 1642.07it/s]

 31%|███       | 3704/12116 [00:02<00:04, 1750.87it/s]

 35%|███▍      | 4208/12116 [00:02<00:03, 2550.83it/s]

 37%|███▋      | 4491/12116 [00:03<00:06, 1244.72it/s]

 39%|███▉      | 4705/12116 [00:03<00:05, 1244.53it/s]

 41%|████      | 4918/12116 [00:03<00:05, 1349.05it/s]

 42%|████▏     | 5124/12116 [00:03<00:06, 1100.35it/s]

 44%|████▎     | 5276/12116 [00:04<00:13, 493.22it/s] 

 44%|████▍     | 5387/12116 [00:04<00:12, 526.88it/s]

 45%|████▌     | 5511/12116 [00:04<00:11, 575.76it/s]

 46%|████▋     | 5607/12116 [00:06<00:29, 217.17it/s]

 47%|████▋     | 5676/12116 [00:07<00:41, 154.87it/s]

 47%|████▋     | 5727/12116 [00:08<00:58, 108.49it/s]

 48%|████▊     | 5802/12116 [00:09<00:53, 118.55it/s]

 48%|████▊     | 5833/12116 [00:09<00:53, 118.48it/s]

 49%|████▊     | 5885/12116 [00:09<00:44, 139.26it/s]

 49%|████▉     | 5919/12116 [00:10<00:49, 125.40it/s]

 50%|████▉     | 6012/12116 [00:10<00:35, 171.37it/s]

 50%|████▉     | 6039/12116 [00:11<01:14, 81.08it/s] 

 50%|█████     | 6058/12116 [00:12<01:49, 55.40it/s]

 50%|█████     | 6072/12116 [00:13<02:11, 45.89it/s]

 50%|█████     | 6083/12116 [00:13<02:13, 45.23it/s]

 50%|█████     | 6092/12116 [00:14<02:27, 40.82it/s]

 50%|█████     | 6099/12116 [00:14<02:37, 38.27it/s]

 50%|█████     | 6105/12116 [00:14<03:12, 31.29it/s]

 50%|█████     | 6110/12116 [00:15<03:27, 28.89it/s]

 50%|█████     | 6114/12116 [00:15<04:16, 23.36it/s]

 50%|█████     | 6117/12116 [00:15<04:24, 22.67it/s]

 51%|█████     | 6120/12116 [00:15<04:24, 22.64it/s]

 51%|█████     | 6123/12116 [00:15<04:50, 20.62it/s]

 51%|█████     | 6126/12116 [00:16<09:14, 10.81it/s]

 51%|█████     | 6203/12116 [00:16<01:23, 70.72it/s]

 51%|█████▏    | 6213/12116 [00:18<03:10, 30.93it/s]

 51%|█████▏    | 6221/12116 [00:18<03:11, 30.82it/s]

 51%|█████▏    | 6235/12116 [00:18<02:38, 37.12it/s]

 52%|█████▏    | 6242/12116 [00:19<02:50, 34.38it/s]

 52%|█████▏    | 6256/12116 [00:19<02:13, 43.77it/s]

 53%|█████▎    | 6375/12116 [00:19<00:32, 175.97it/s]

 53%|█████▎    | 6408/12116 [00:20<01:05, 86.85it/s] 

 53%|█████▎    | 6433/12116 [00:20<01:00, 93.60it/s]

 55%|█████▍    | 6658/12116 [00:20<00:18, 300.96it/s]

 56%|█████▌    | 6730/12116 [00:21<00:33, 161.36it/s]

 56%|█████▌    | 6783/12116 [00:22<00:32, 164.00it/s]

 56%|█████▋    | 6825/12116 [00:22<00:39, 133.69it/s]

 57%|█████▋    | 6857/12116 [00:24<01:19, 66.07it/s] 

 57%|█████▋    | 6880/12116 [00:24<01:14, 69.94it/s]

 57%|█████▋    | 6899/12116 [00:24<01:20, 64.84it/s]

 57%|█████▋    | 6914/12116 [00:25<01:15, 69.16it/s]

 57%|█████▋    | 6937/12116 [00:25<01:13, 70.65it/s]

 57%|█████▋    | 6949/12116 [00:25<01:09, 73.95it/s]

 58%|█████▊    | 6986/12116 [00:25<00:47, 107.81it/s]

 58%|█████▊    | 7005/12116 [00:25<00:47, 108.11it/s]

 58%|█████▊    | 7027/12116 [00:25<00:42, 120.39it/s]

 58%|█████▊    | 7044/12116 [00:26<00:46, 109.17it/s]

 58%|█████▊    | 7058/12116 [00:26<01:15, 66.84it/s] 

 59%|█████▊    | 7092/12116 [00:26<00:50, 100.05it/s]

 59%|█████▊    | 7109/12116 [00:27<01:05, 75.98it/s] 

 59%|█████▉    | 7124/12116 [00:27<01:06, 74.82it/s]

 60%|██████    | 7323/12116 [00:27<00:17, 275.69it/s]

 61%|██████    | 7377/12116 [00:27<00:16, 292.44it/s]

 61%|██████    | 7409/12116 [00:28<00:20, 227.39it/s]

 63%|██████▎   | 7578/12116 [00:28<00:11, 410.77it/s]

 64%|██████▍   | 7726/12116 [00:28<00:07, 575.90it/s]

 64%|██████▍   | 7803/12116 [00:29<00:24, 175.83it/s]

 65%|██████▍   | 7859/12116 [00:30<00:31, 133.85it/s]

 65%|██████▌   | 7900/12116 [00:31<00:38, 109.61it/s]

 65%|██████▌   | 7931/12116 [00:31<00:37, 110.28it/s]

 66%|██████▌   | 7956/12116 [00:31<00:35, 118.46it/s]

 66%|██████▌   | 7980/12116 [00:31<00:35, 116.12it/s]

 67%|██████▋   | 8129/12116 [00:32<00:18, 212.60it/s]

 67%|██████▋   | 8157/12116 [00:32<00:23, 165.89it/s]

 68%|██████▊   | 8179/12116 [00:32<00:26, 148.60it/s]

 68%|██████▊   | 8225/12116 [00:32<00:21, 182.13it/s]

 68%|██████▊   | 8250/12116 [00:33<00:32, 117.58it/s]

 68%|██████▊   | 8269/12116 [00:34<00:54, 70.57it/s] 

 70%|██████▉   | 8429/12116 [00:34<00:19, 192.78it/s]

 70%|███████   | 8483/12116 [00:34<00:17, 207.76it/s]

 70%|███████   | 8529/12116 [00:35<00:28, 127.74it/s]

 71%|███████   | 8567/12116 [00:35<00:25, 139.90it/s]

 71%|███████   | 8598/12116 [00:37<01:11, 49.43it/s] 

 71%|███████   | 8620/12116 [00:38<01:14, 46.81it/s]

 71%|███████▏  | 8637/12116 [00:38<01:08, 51.07it/s]

 71%|███████▏  | 8652/12116 [00:40<01:49, 31.77it/s]

 72%|███████▏  | 8663/12116 [00:41<02:32, 22.59it/s]

 72%|███████▏  | 8698/12116 [00:41<01:37, 34.96it/s]

 72%|███████▏  | 8710/12116 [00:42<01:53, 29.93it/s]

 72%|███████▏  | 8720/12116 [00:42<01:43, 32.90it/s]

 72%|███████▏  | 8728/12116 [00:43<02:31, 22.33it/s]

 73%|███████▎  | 8871/12116 [00:43<00:31, 104.03it/s]

 74%|███████▎  | 8911/12116 [00:44<00:40, 79.91it/s] 

 74%|███████▍  | 8940/12116 [00:44<00:35, 88.67it/s]

 75%|███████▍  | 9041/12116 [00:44<00:19, 157.20it/s]

 75%|███████▍  | 9080/12116 [00:45<00:26, 112.98it/s]

 75%|███████▌  | 9109/12116 [00:45<00:24, 125.20it/s]

 77%|███████▋  | 9385/12116 [00:45<00:06, 393.60it/s]

 78%|███████▊  | 9480/12116 [00:45<00:06, 425.78it/s]

 80%|███████▉  | 9680/12116 [00:45<00:04, 594.75it/s]

 81%|████████  | 9775/12116 [00:47<00:09, 246.75it/s]

 81%|████████  | 9844/12116 [00:47<00:09, 249.41it/s]

 82%|████████▏ | 9900/12116 [00:47<00:11, 187.06it/s]

 82%|████████▏ | 9942/12116 [00:48<00:11, 190.24it/s]

 82%|████████▏ | 9978/12116 [00:48<00:16, 127.23it/s]

 83%|████████▎ | 10005/12116 [00:49<00:20, 100.77it/s]

 83%|████████▎ | 10025/12116 [00:49<00:19, 105.62it/s]

 83%|████████▎ | 10044/12116 [00:50<00:27, 74.30it/s] 

 83%|████████▎ | 10065/12116 [00:50<00:26, 77.13it/s]

 84%|████████▍ | 10159/12116 [00:50<00:12, 158.83it/s]

 86%|████████▋ | 10460/12116 [00:50<00:03, 441.08it/s]

 87%|████████▋ | 10529/12116 [00:50<00:03, 467.53it/s]

 91%|█████████ | 11036/12116 [00:51<00:00, 1184.33it/s]

 93%|█████████▎| 11235/12116 [00:51<00:00, 1250.33it/s]

 94%|█████████▍| 11419/12116 [00:51<00:00, 1305.39it/s]

 96%|█████████▌| 11592/12116 [00:51<00:00, 1154.15it/s]

 98%|█████████▊| 11911/12116 [00:51<00:00, 1560.27it/s]

100%|██████████| 12116/12116 [00:51<00:00, 234.49it/s] 

Joining sequences to metadata...


  0%|          | 0/18966 [00:00<?, ?it/s]

 30%|██▉       | 5668/18966 [00:00<00:00, 56672.62it/s]

 73%|███████▎  | 13807/18966 [00:00<00:00, 71208.92it/s]

100%|██████████| 18966/18966 [00:00<00:00, 72902.50it/s]

Sequences with content: 17989 / 18966  (94.8%)


## 3. Exploratory Data Analysis

In [6]:
colors = {'Normal': '#4C72B0', 'Attack': '#DD8452'}

# -- Class distribution -------------------------------------------------------
counts = df['label_name'].value_counts()
fig, axes = plt.subplots(1, 2, figsize=(13, 4))
axes[0].bar(counts.index, counts.values, color=[colors[k] for k in counts.index],
            width=0.5, edgecolor='white')
for i, (lbl, v) in enumerate(counts.items()):
    axes[0].text(i, v + 100, f'{v:,}', ha='center', fontsize=11)
axes[0].set_title('Class Distribution'); axes[0].set_ylabel('Sequences')
axes[1].pie(counts.values, labels=counts.index, colors=[colors[k] for k in counts.index],
            autopct='%1.1f%%', startangle=90, textprops={'fontsize': 12})
axes[1].set_title('Class Balance')
plt.suptitle('DongTing Dataset', fontsize=14)
plt.tight_layout(); plt.savefig(f'{OUT}/eda_class_dist.png', dpi=150); plt.show()
print(counts.to_string())


label_name
Attack    12116
Normal     6850


In [7]:
# -- Sequence length distribution per class -----------------------------------
fig, axes = plt.subplots(1, 2, figsize=(14, 4))
for ax, lbl, cap in [(axes[0], 'Normal', 5000), (axes[1], 'Attack', 200000)]:
    sub = df[df.label_name == lbl]['seq_len'].clip(upper=cap)
    ax.hist(sub, bins=60, color=colors[lbl], alpha=0.85, edgecolor='white')
    ax.axvline(sub.median(), color='black', linestyle='--', label=f'median={sub.median():.0f}')
    ax.set_title(f'{lbl} — Sequence Length (capped {cap:,})')
    ax.set_xlabel('Syscall Count'); ax.set_ylabel('Sequences'); ax.legend()
plt.suptitle('Sequence Length Distribution by Class', fontsize=13)
plt.tight_layout(); plt.savefig(f'{OUT}/eda_seq_len.png', dpi=150); plt.show()
print(df.groupby('label_name')['seq_len'].describe().round(1))


              count     mean       std  min   25%   50%     75%        max
label_name                                                                
Attack      12116.0  34832.2  200393.3  0.0  31.0  34.0  2697.5  2722485.0
Normal       6850.0   7202.2   64927.9  0.0  42.0  61.0   126.0  1419684.0


In [8]:
# -- Kernel version distribution ----------------------------------------------
ver_label = df.groupby(['kcb_master_line_ver', 'label_name']).size().unstack(fill_value=0)
fig, ax = plt.subplots(figsize=(13, 4))
ver_label.plot(kind='bar', ax=ax, color=[colors['Attack'], colors['Normal']],
               alpha=0.85, edgecolor='white')
ax.set_title('Sequences per Kernel Version'); ax.set_xlabel('Kernel Version')
ax.set_ylabel('Count'); ax.legend(title='Label'); plt.xticks(rotation=45)
plt.tight_layout(); plt.savefig(f'{OUT}/eda_kernel_versions.png', dpi=150); plt.show()


In [9]:
# -- Discriminative syscalls --------------------------------------------------
def top_syscalls(seqs, n=400):
    cnt = collections.Counter()
    for s in seqs:
        cnt.update(set(s))   # per-sequence presence
    return cnt.most_common(n)

total_normal = (df.label == 0).sum()
total_attack = (df.label == 1).sum()
normal_freq = {k: v / total_normal for k, v in dict(top_syscalls(df[df.label==0]['seq'])).items()}
attack_freq = {k: v / total_attack for k, v in dict(top_syscalls(df[df.label==1]['seq'])).items()}
all_ids = set(normal_freq) | set(attack_freq)
diff = {k: attack_freq.get(k, 0) - normal_freq.get(k, 0) for k in all_ids}

top_attack_excl = sorted(diff.items(), key=lambda x: x[1],  reverse=True)[:20]
top_normal_excl = sorted(diff.items(), key=lambda x: x[1])[:20]

fig, axes = plt.subplots(1, 2, figsize=(16, 5))
for ax, data, title, clr in [
    (axes[0], top_attack_excl, 'Top Attack-Exclusive Syscalls', colors['Attack']),
    (axes[1], top_normal_excl, 'Top Normal-Exclusive Syscalls', colors['Normal']),
]:
    names = [id_to_name(k) for k, _ in data]
    vals  = [abs(v) for _, v in data]
    ax.barh(names[::-1], vals[::-1], color=clr, alpha=0.85)
    ax.set_title(title); ax.set_xlabel('|attack_rate − normal_rate|')
plt.suptitle('Discriminative Syscalls — DongTing', fontsize=13)
plt.tight_layout(); plt.savefig(f'{OUT}/eda_discriminative_syscalls.png', dpi=150); plt.show()

print('Top-10 attack-exclusive:')
for sid, d in top_attack_excl[:10]:
    print(f'  {id_to_name(sid):20s}  diff={d:+.3f}  atk={attack_freq.get(sid,0):.3f}  nor={normal_freq.get(sid,0):.3f}')


Top-10 attack-exclusive:
  execve                diff=+0.919  atk=0.919  nor=0.000
  ioctl                 diff=+0.371  atk=0.371  nor=0.000
  prctl                 diff=+0.356  atk=0.376  nor=0.020
  socket                diff=+0.351  atk=0.418  nor=0.067
  open                  diff=+0.324  atk=0.324  nor=0.000
  fstat                 diff=+0.312  atk=0.317  nor=0.005
  sendmsg               diff=+0.223  atk=0.223  nor=0.000
  setsid                diff=+0.191  atk=0.197  nor=0.006
  unshare               diff=+0.187  atk=0.199  nor=0.012
  mount                 diff=+0.184  atk=0.204  nor=0.020


In [10]:
# -- Syscall bigrams ----------------------------------------------------------
BIGRAM_SAMPLE = 2000
def top_bigrams(seqs, n=20, limit=BIGRAM_SAMPLE):
    cnt = collections.Counter()
    for s in seqs[:limit]:
        for a, b in zip(s, s[1:]):
            cnt[(a, b)] += 1
    return cnt.most_common(n)

norm_bg = top_bigrams(df[df.label==0]['seq'].tolist())
atk_bg  = top_bigrams(df[df.label==1]['seq'].tolist())
print('Top-10 Normal bigrams:')
for (a, b), c in norm_bg[:10]:
    print(f'  {id_to_name(a)}→{id_to_name(b)}  ({c})')
print('\nTop-10 Attack bigrams:')
for (a, b), c in atk_bg[:10]:
    print(f'  {id_to_name(a)}→{id_to_name(b)}  ({c})')


Top-10 Normal bigrams:
  futex→futex  (2114319)
  write→write  (1648881)
  sysinfo→sysinfo  (1099998)
  ioctl→ioctl  (690924)
  mmap→munmap  (397879)
  munmap→mmap  (370182)
  mprotect→mprotect  (237120)
  openat→newfstatat  (217280)
  connect→connect  (216731)
  read→close  (198735)

Top-10 Attack bigrams:
  wait4→nanosleep  (6193043)
  exit_group→wait4  (5501712)
  socket→connect  (5393144)
  nanosleep→wait4  (4960000)
  clone→wait4  (4838190)
  mmap→socket  (4595235)
  close→close  (4367356)
  socket→close  (4175621)
  setpgid→mmap  (4034642)
  wait4→prctl  (3877899)


## 4. Feature Engineering — 174-dim

Five feature groups:

| Group | Dims | Description |
|---|---|---|
| `freq_60` | 60 | Relative frequency of top-60 syscall IDs per sequence |
| `disc_40` | 40 | Binary presence of top-20 attack-exclusive + top-20 normal-exclusive syscalls |
| `stats_8` | 8 | Sequence statistics: log-len, log-unique, diversity, entropy, log-count, log-size, mean-ID, std-ID |
| `bigram_40` | 40 | Relative frequency of top-40 discriminative syscall transition pairs |
| `ver_onehot` | ~26 | One-hot kernel version |


In [11]:
# -- Feature group definitions ------------------------------------------------
all_top = pd.Series(
    {k: normal_freq.get(k, 0) + attack_freq.get(k, 0) for k in all_ids}
).sort_values(ascending=False)
TOP_IDS = all_top.head(60).index.tolist()

DISC_IDS = [k for k, _ in top_attack_excl[:20]] + [k for k, _ in top_normal_excl[:20]]

all_bg_norm = dict(top_bigrams(df[df.label==0]['seq'].tolist(), n=200))
all_bg_atk  = dict(top_bigrams(df[df.label==1]['seq'].tolist(), n=200))
all_bg_keys = set(all_bg_norm) | set(all_bg_atk)
bg_diff = {k: all_bg_atk.get(k, 0) / max(1, total_attack)
              - all_bg_norm.get(k, 0) / max(1, total_normal)
           for k in all_bg_keys}
TOP_BIGRAMS = [k for k, _ in sorted(bg_diff.items(), key=lambda x: abs(x[1]), reverse=True)[:40]]

ver_cols = sorted(df['kcb_master_line_ver'].unique())

feature_groups = {
    'freq_60':    len(TOP_IDS),
    'disc_40':    len(DISC_IDS),
    'stats_8':    8,
    'bigram_40':  len(TOP_BIGRAMS),
    'ver_onehot': len(ver_cols),
}
total_dims = sum(feature_groups.values())
print('Feature groups:', feature_groups)
print(f'Total dimensions: {total_dims}')


Feature groups: {'freq_60': 60, 'disc_40': 40, 'stats_8': 8, 'bigram_40': 40, 'ver_onehot': 26}
Total dimensions: 174


In [12]:
def feat_freq(seq):
    if not seq: return np.zeros(len(TOP_IDS), dtype=np.float32)
    t = len(seq)
    return np.array([seq.count(s) / t for s in TOP_IDS], dtype=np.float32)

def feat_disc(seq):
    s = set(seq)
    return np.array([1.0 if d in s else 0.0 for d in DISC_IDS], dtype=np.float32)

def feat_stats(seq, counts, sizes):
    if not seq: return np.zeros(8, dtype=np.float32)
    arr  = np.array(seq)
    freq = np.bincount(arr[arr >= 0], minlength=548).astype(np.float32)
    freq /= (freq.sum() + 1e-9)
    ent  = float(scipy_entropy(freq + 1e-9))
    return np.array([
        np.log1p(len(seq)), np.log1p(len(set(seq))),
        len(set(seq)) / (len(seq) + 1e-9), ent,
        np.log1p(counts), np.log1p(sizes),
        float(np.mean(arr)), float(np.std(arr)),
    ], dtype=np.float32)

def feat_bigrams(seq):
    if len(seq) < 2: return np.zeros(len(TOP_BIGRAMS), dtype=np.float32)
    cnt = collections.Counter(zip(seq, seq[1:]))
    total = sum(cnt.values()) + 1e-9
    return np.array([cnt.get(bg, 0) / total for bg in TOP_BIGRAMS], dtype=np.float32)

def feat_ver(ver):
    return np.array([1.0 if v == ver else 0.0 for v in ver_cols], dtype=np.float32)

print('Building feature matrix...')
rows = []
for _, row in tqdm(df.iterrows(), total=len(df), desc='features'):
    seq = row['seq']
    rows.append(np.concatenate([
        feat_freq(seq), feat_disc(seq),
        feat_stats(seq, row['syscall_counts'], row['syscall_sizes']),
        feat_bigrams(seq), feat_ver(row['kcb_master_line_ver']),
    ]))

X_all = np.array(rows, dtype=np.float32)
X_all = np.nan_to_num(X_all, nan=0.0, posinf=0.0, neginf=0.0)
y_all = df['label'].values
print(f'Feature matrix: {X_all.shape}  NaN={np.isnan(X_all).sum()}  Inf={np.isinf(X_all).sum()}')


Building feature matrix...


features:   0%|          | 0/18966 [00:00<?, ?it/s]

features:   0%|          | 6/18966 [00:00<37:17,  8.47it/s]

features:   0%|          | 39/18966 [00:00<05:05, 61.89it/s]

features:   0%|          | 89/18966 [00:00<02:09, 145.69it/s]

features:   1%|          | 133/18966 [00:01<01:30, 208.80it/s]

features:   1%|          | 178/18966 [00:01<01:14, 250.76it/s]

features:   1%|          | 215/18966 [00:08<21:04, 14.83it/s] 

features:   1%|▏         | 240/18966 [00:13<29:30, 10.58it/s]

features:   1%|▏         | 257/18966 [00:15<31:54,  9.77it/s]

features:   1%|▏         | 269/18966 [00:17<33:47,  9.22it/s]

features:   1%|▏         | 278/18966 [00:19<38:44,  8.04it/s]

features:   1%|▏         | 284/18966 [00:20<41:47,  7.45it/s]

features:   2%|▏         | 289/18966 [00:22<54:07,  5.75it/s]

features:   2%|▏         | 292/18966 [00:24<1:07:34,  4.61it/s]

features:   2%|▏         | 295/18966 [00:25<1:08:20,  4.55it/s]

features:   2%|▏         | 297/18966 [00:25<1:09:15,  4.49it/s]

features:   2%|▏         | 299/18966 [00:26<1:06:08,  4.70it/s]

features:   2%|▏         | 301/18966 [00:26<1:01:19,  5.07it/s]

features:   2%|▏         | 303/18966 [00:26<57:47,  5.38it/s]  

features:   2%|▏         | 305/18966 [00:26<52:26,  5.93it/s]

features:   2%|▏         | 308/18966 [00:26<39:57,  7.78it/s]

features:   2%|▏         | 310/18966 [00:27<57:36,  5.40it/s]

features:   2%|▏         | 312/18966 [00:28<1:12:02,  4.32it/s]

features:   2%|▏         | 313/18966 [00:28<1:29:10,  3.49it/s]

features:   2%|▏         | 314/18966 [00:29<1:46:03,  2.93it/s]

features:   2%|▏         | 316/18966 [00:29<1:33:14,  3.33it/s]

features:   2%|▏         | 318/18966 [00:30<1:28:02,  3.53it/s]

features:   2%|▏         | 341/18966 [00:30<15:33, 19.95it/s]  

features:   2%|▏         | 353/18966 [00:30<10:55, 28.40it/s]

features:   3%|▎         | 544/18966 [00:31<01:34, 195.23it/s]

features:   3%|▎         | 575/18966 [00:31<02:18, 132.65it/s]

features:   3%|▎         | 593/18966 [00:31<02:28, 123.47it/s]

features:   3%|▎         | 608/18966 [00:32<03:25, 89.39it/s] 

features:   4%|▎         | 679/18966 [00:32<02:01, 150.62it/s]

features:   4%|▍         | 733/18966 [00:32<01:31, 198.49it/s]

features:   4%|▍         | 838/18966 [00:32<00:55, 324.49it/s]

features:   5%|▍         | 894/18966 [00:32<00:50, 355.09it/s]

features:   5%|▌         | 974/18966 [00:32<00:42, 427.51it/s]

features:   6%|▌         | 1107/18966 [00:33<00:28, 619.29it/s]

features:   6%|▋         | 1200/18966 [00:33<00:25, 690.19it/s]

features:   7%|▋         | 1284/18966 [00:33<00:28, 630.33it/s]

features:   7%|▋         | 1379/18966 [00:33<00:25, 694.01it/s]

features:   8%|▊         | 1458/18966 [00:35<02:42, 107.65it/s]

features:   8%|▊         | 1514/18966 [00:36<02:44, 105.78it/s]

features:   8%|▊         | 1557/18966 [00:38<05:22, 54.05it/s] 

features:   8%|▊         | 1588/18966 [00:38<04:44, 61.12it/s]

features:   9%|▉         | 1742/18966 [00:39<02:16, 126.19it/s]

features:  10%|▉         | 1802/18966 [00:41<04:08, 68.96it/s] 

features:  10%|▉         | 1869/18966 [00:41<03:20, 85.21it/s]

features:  10%|█         | 1906/18966 [00:42<04:18, 66.06it/s]

features:  10%|█         | 1933/18966 [00:43<05:17, 53.69it/s]

features:  10%|█         | 1961/18966 [00:44<05:04, 55.93it/s]

features:  10%|█         | 1977/18966 [00:44<06:18, 44.89it/s]

features:  10%|█         | 1990/18966 [00:45<06:30, 43.50it/s]

features:  11%|█         | 2007/18966 [00:45<07:13, 39.13it/s]

features:  11%|█         | 2015/18966 [00:46<07:43, 36.59it/s]

features:  11%|█         | 2026/18966 [00:46<09:02, 31.25it/s]

features:  11%|█         | 2035/18966 [00:47<08:51, 31.87it/s]

features:  11%|█         | 2050/18966 [00:47<09:14, 30.52it/s]

features:  11%|█         | 2055/18966 [00:47<09:34, 29.43it/s]

features:  11%|█         | 2067/18966 [00:48<08:53, 31.67it/s]

features:  11%|█         | 2071/18966 [00:48<13:55, 20.23it/s]

features:  11%|█         | 2074/18966 [00:49<20:41, 13.60it/s]

features:  11%|█         | 2076/18966 [00:49<24:38, 11.42it/s]

features:  11%|█         | 2078/18966 [00:50<27:25, 10.26it/s]

features:  11%|█         | 2118/18966 [00:50<06:31, 42.99it/s]

features:  11%|█▏        | 2150/18966 [00:50<03:52, 72.39it/s]

features:  12%|█▏        | 2188/18966 [00:50<02:28, 113.02it/s]

features:  12%|█▏        | 2287/18966 [00:50<01:06, 250.83it/s]

features:  12%|█▏        | 2333/18966 [00:50<01:07, 247.04it/s]

features:  13%|█▎        | 2372/18966 [00:51<02:21, 117.26it/s]

features:  13%|█▎        | 2402/18966 [00:51<02:02, 135.72it/s]

features:  13%|█▎        | 2432/18966 [00:51<01:46, 155.11it/s]

features:  14%|█▎        | 2577/18966 [00:52<00:46, 351.15it/s]

features:  14%|█▍        | 2641/18966 [00:52<00:44, 370.91it/s]

features:  14%|█▍        | 2699/18966 [01:01<11:57, 22.66it/s] 

features:  15%|█▍        | 2771/18966 [01:01<08:12, 32.86it/s]

features:  15%|█▍        | 2818/18966 [01:06<13:38, 19.73it/s]

features:  15%|█▌        | 2856/18966 [01:07<11:22, 23.60it/s]

features:  15%|█▌        | 2882/18966 [01:07<10:05, 26.57it/s]

features:  15%|█▌        | 2906/18966 [01:08<09:03, 29.57it/s]

features:  15%|█▌        | 2922/18966 [01:10<13:22, 19.99it/s]

features:  16%|█▌        | 2952/18966 [01:10<10:01, 26.62it/s]

features:  16%|█▌        | 2965/18966 [01:10<08:53, 30.01it/s]

features:  16%|█▌        | 2978/18966 [01:10<07:45, 34.36it/s]

features:  17%|█▋        | 3160/18966 [01:11<01:48, 145.93it/s]

features:  18%|█▊        | 3350/18966 [01:11<00:53, 289.66it/s]

features:  18%|█▊        | 3451/18966 [01:11<00:48, 321.89it/s]

features:  19%|█▊        | 3535/18966 [01:18<05:59, 42.96it/s] 

features:  19%|█▉        | 3595/18966 [01:19<06:13, 41.19it/s]

features:  19%|█▉        | 3680/18966 [01:20<05:08, 49.57it/s]

features:  20%|█▉        | 3715/18966 [01:20<04:28, 56.72it/s]

features:  20%|█▉        | 3748/18966 [01:21<03:53, 65.31it/s]

features:  20%|██        | 3795/18966 [01:21<03:02, 83.21it/s]

features:  20%|██        | 3830/18966 [01:21<02:37, 95.90it/s]

features:  21%|██        | 3891/18966 [01:21<01:51, 135.01it/s]

features:  21%|██        | 3931/18966 [01:23<05:16, 47.55it/s] 

features:  21%|██        | 3960/18966 [01:25<06:55, 36.11it/s]

features:  21%|██▏       | 4062/18966 [01:25<03:32, 70.23it/s]

features:  22%|██▏       | 4164/18966 [01:26<02:42, 91.03it/s]

features:  22%|██▏       | 4200/18966 [01:27<03:13, 76.24it/s]

features:  22%|██▏       | 4227/18966 [01:27<02:56, 83.29it/s]

features:  22%|██▏       | 4251/18966 [01:27<03:23, 72.27it/s]

features:  23%|██▎       | 4305/18966 [01:27<02:31, 96.66it/s]

features:  23%|██▎       | 4326/18966 [01:28<02:31, 96.80it/s]

features:  23%|██▎       | 4373/18966 [01:28<01:49, 132.79it/s]

features:  24%|██▍       | 4638/18966 [01:28<00:32, 437.61it/s]

features:  25%|██▌       | 4799/18966 [01:28<00:23, 607.91it/s]

features:  26%|██▌       | 4915/18966 [01:28<00:20, 696.63it/s]

features:  27%|██▋       | 5029/18966 [01:30<01:13, 190.66it/s]

features:  27%|██▋       | 5111/18966 [01:30<01:00, 227.17it/s]

features:  27%|██▋       | 5188/18966 [01:30<00:55, 249.00it/s]

features:  28%|██▊       | 5253/18966 [01:31<01:40, 136.62it/s]

features:  29%|██▊       | 5426/18966 [01:31<00:57, 235.31it/s]

features:  29%|██▉       | 5511/18966 [01:33<01:50, 121.66it/s]

features:  29%|██▉       | 5572/18966 [01:33<01:36, 138.63it/s]

features:  30%|██▉       | 5640/18966 [01:34<01:18, 170.17it/s]

features:  30%|███       | 5695/18966 [01:37<03:36, 61.25it/s] 

features:  30%|███       | 5734/18966 [01:39<05:43, 38.54it/s]

features:  30%|███       | 5777/18966 [01:39<04:33, 48.22it/s]

features:  31%|███       | 5841/18966 [01:39<03:11, 68.42it/s]

features:  31%|███       | 5882/18966 [01:40<03:04, 70.73it/s]

features:  32%|███▏      | 6042/18966 [01:40<01:25, 150.73it/s]

features:  32%|███▏      | 6125/18966 [01:40<01:05, 196.40it/s]

features:  33%|███▎      | 6193/18966 [01:41<01:09, 184.00it/s]

features:  33%|███▎      | 6251/18966 [01:41<00:59, 215.16it/s]

features:  33%|███▎      | 6302/18966 [01:41<01:15, 168.60it/s]

features:  34%|███▎      | 6363/18966 [01:42<01:40, 125.14it/s]

features:  34%|███▎      | 6393/18966 [01:43<02:23, 87.71it/s] 

features:  34%|███▍      | 6418/18966 [01:44<03:26, 60.76it/s]

features:  34%|███▍      | 6434/18966 [01:48<09:16, 22.50it/s]

features:  34%|███▍      | 6446/18966 [01:50<14:01, 14.89it/s]

features:  35%|███▌      | 6684/18966 [01:51<03:47, 54.11it/s]

features:  35%|███▌      | 6697/18966 [02:01<12:14, 16.70it/s]

features:  35%|███▌      | 6706/18966 [02:02<12:48, 15.95it/s]

features:  36%|███▌      | 6815/18966 [02:02<06:44, 30.01it/s]

features:  36%|███▌      | 6839/18966 [02:06<09:22, 21.56it/s]

features:  36%|███▌      | 6856/18966 [02:06<09:38, 20.94it/s]

features:  36%|███▌      | 6869/18966 [02:07<09:39, 20.88it/s]

features:  36%|███▋      | 6879/18966 [02:08<11:30, 17.51it/s]

features:  36%|███▋      | 6886/18966 [02:10<14:08, 14.25it/s]

features:  36%|███▋      | 6891/18966 [02:12<20:54,  9.63it/s]

features:  37%|███▋      | 7023/18966 [02:12<04:43, 42.14it/s]

features:  37%|███▋      | 7065/18966 [02:12<03:37, 54.83it/s]

features:  37%|███▋      | 7106/18966 [02:12<02:48, 70.54it/s]

features:  38%|███▊      | 7148/18966 [02:12<02:12, 89.37it/s]

features:  38%|███▊      | 7184/18966 [02:13<02:49, 69.40it/s]

features:  38%|███▊      | 7210/18966 [02:15<05:35, 35.00it/s]

features:  38%|███▊      | 7231/18966 [02:16<04:41, 41.72it/s]

features:  39%|███▊      | 7312/18966 [02:16<02:36, 74.46it/s]

features:  39%|███▉      | 7375/18966 [02:16<01:45, 109.69it/s]

features:  39%|███▉      | 7409/18966 [02:16<01:59, 96.40it/s] 

features:  39%|███▉      | 7489/18966 [02:17<01:59, 95.81it/s]

features:  40%|███▉      | 7510/18966 [02:18<03:09, 60.57it/s]

features:  40%|███▉      | 7575/18966 [02:19<02:04, 91.78it/s]

features:  40%|████      | 7604/18966 [02:19<01:54, 99.49it/s]

features:  41%|████      | 7715/18966 [02:19<01:00, 185.16it/s]

features:  41%|████▏     | 7835/18966 [02:19<00:44, 252.98it/s]

features:  42%|████▏     | 7882/18966 [02:20<01:07, 163.82it/s]

features:  42%|████▏     | 7936/18966 [02:20<00:55, 197.19it/s]

features:  42%|████▏     | 8016/18966 [02:20<00:41, 265.71it/s]

features:  43%|████▎     | 8069/18966 [02:20<00:49, 221.91it/s]

features:  43%|████▎     | 8142/18966 [02:20<00:38, 283.03it/s]

features:  43%|████▎     | 8197/18966 [02:21<00:33, 323.65it/s]

features:  43%|████▎     | 8248/18966 [02:24<03:32, 50.55it/s] 

features:  44%|████▍     | 8346/18966 [02:24<02:08, 82.55it/s]

features:  44%|████▍     | 8401/18966 [02:24<01:41, 104.56it/s]

features:  45%|████▍     | 8453/18966 [02:24<01:23, 126.40it/s]

features:  45%|████▌     | 8551/18966 [02:24<00:53, 194.90it/s]

features:  45%|████▌     | 8613/18966 [02:25<00:44, 234.00it/s]

features:  46%|████▌     | 8672/18966 [02:25<00:37, 274.49it/s]

features:  46%|████▌     | 8729/18966 [02:27<02:08, 79.74it/s] 

features:  46%|████▌     | 8770/18966 [02:27<01:58, 86.07it/s]

features:  46%|████▋     | 8803/18966 [02:28<02:12, 76.97it/s]

features:  47%|████▋     | 8838/18966 [02:28<01:47, 93.91it/s]

features:  47%|████▋     | 8868/18966 [02:28<01:31, 110.69it/s]

features:  47%|████▋     | 8897/18966 [02:30<04:30, 37.28it/s] 

features:  47%|████▋     | 8917/18966 [02:31<04:11, 39.95it/s]

features:  47%|████▋     | 8933/18966 [02:32<05:28, 30.53it/s]

features:  47%|████▋     | 8945/18966 [02:33<06:13, 26.80it/s]

features:  47%|████▋     | 8975/18966 [02:33<04:24, 37.76it/s]

features:  47%|████▋     | 8985/18966 [02:33<04:32, 36.69it/s]

features:  48%|████▊     | 9038/18966 [02:33<02:17, 71.99it/s]

features:  48%|████▊     | 9066/18966 [02:33<01:49, 90.49it/s]

features:  48%|████▊     | 9089/18966 [02:34<01:42, 96.54it/s]

features:  49%|████▉     | 9247/18966 [02:34<00:34, 284.63it/s]

features:  49%|████▉     | 9302/18966 [02:34<00:35, 274.10it/s]

features:  49%|████▉     | 9365/18966 [02:35<00:53, 178.21it/s]

features:  50%|████▉     | 9411/18966 [02:35<01:22, 115.64it/s]

features:  50%|████▉     | 9438/18966 [02:36<01:44, 91.01it/s] 

features:  50%|█████     | 9504/18966 [02:36<01:11, 132.89it/s]

features:  50%|█████     | 9537/18966 [02:39<04:16, 36.79it/s] 

features:  50%|█████     | 9562/18966 [02:40<04:28, 35.00it/s]

features:  51%|█████     | 9591/18966 [02:40<03:33, 44.01it/s]

features:  51%|█████     | 9613/18966 [02:41<02:58, 52.42it/s]

features:  51%|█████     | 9634/18966 [02:42<03:51, 40.32it/s]

features:  51%|█████     | 9650/18966 [02:44<07:26, 20.86it/s]

features:  51%|█████     | 9661/18966 [02:45<09:45, 15.89it/s]

features:  51%|█████     | 9669/18966 [02:46<08:57, 17.30it/s]

features:  51%|█████▏    | 9723/18966 [02:46<03:57, 38.92it/s]

features:  51%|█████▏    | 9753/18966 [02:46<03:19, 46.07it/s]

features:  52%|█████▏    | 9832/18966 [02:46<01:37, 93.68it/s]

features:  52%|█████▏    | 9871/18966 [02:46<01:16, 118.35it/s]

features:  52%|█████▏    | 9912/18966 [02:46<01:00, 149.01it/s]

features:  52%|█████▏    | 9949/18966 [02:47<01:00, 148.62it/s]

features:  53%|█████▎    | 9979/18966 [02:47<01:11, 125.45it/s]

features:  53%|█████▎    | 10003/18966 [02:48<02:30, 59.41it/s]

features:  53%|█████▎    | 10044/18966 [02:49<02:04, 71.42it/s]

features:  53%|█████▎    | 10060/18966 [02:49<02:11, 67.95it/s]

features:  53%|█████▎    | 10079/18966 [02:49<02:11, 67.40it/s]

features:  53%|█████▎    | 10090/18966 [02:49<02:28, 59.84it/s]

features:  54%|█████▎    | 10166/18966 [02:50<01:06, 132.09it/s]

features:  54%|█████▎    | 10193/18966 [02:50<01:09, 126.47it/s]

features:  54%|█████▍    | 10216/18966 [02:50<01:32, 94.10it/s] 

features:  54%|█████▍    | 10233/18966 [02:51<02:22, 61.35it/s]

features:  55%|█████▍    | 10363/18966 [02:51<00:50, 170.29it/s]

features:  55%|█████▍    | 10409/18966 [02:51<00:49, 174.62it/s]

features:  56%|█████▌    | 10570/18966 [02:51<00:24, 348.44it/s]

features:  56%|█████▌    | 10645/18966 [02:52<00:24, 337.63it/s]

features:  57%|█████▋    | 10786/18966 [02:52<00:16, 486.44it/s]

features:  57%|█████▋    | 10866/18966 [02:52<00:15, 523.63it/s]

features:  58%|█████▊    | 10955/18966 [02:52<00:15, 527.50it/s]

features:  58%|█████▊    | 11030/18966 [02:53<00:33, 234.29it/s]

features:  58%|█████▊    | 11082/18966 [02:55<01:16, 102.99it/s]

features:  59%|█████▉    | 11181/18966 [02:55<00:51, 151.22it/s]

features:  60%|█████▉    | 11293/18966 [02:55<00:35, 214.33it/s]

features:  60%|█████▉    | 11356/18966 [02:55<00:33, 229.89it/s]

features:  60%|██████    | 11435/18966 [02:55<00:26, 286.96it/s]

features:  61%|██████    | 11495/18966 [02:56<00:42, 176.74it/s]

features:  61%|██████    | 11539/18966 [02:56<00:38, 194.65it/s]

features:  61%|██████    | 11616/18966 [02:56<00:31, 235.03it/s]

features:  61%|██████▏   | 11657/18966 [02:57<00:39, 186.89it/s]

features:  62%|██████▏   | 11798/18966 [02:57<00:22, 324.75it/s]

features:  63%|██████▎   | 11858/18966 [02:57<00:20, 341.64it/s]

features:  63%|██████▎   | 11941/18966 [02:57<00:17, 411.73it/s]

features:  63%|██████▎   | 12002/18966 [03:00<01:34, 73.52it/s] 

features:  64%|██████▎   | 12045/18966 [03:00<01:33, 74.21it/s]

features:  64%|██████▍   | 12091/18966 [03:00<01:14, 92.23it/s]

features:  64%|██████▍   | 12128/18966 [03:01<01:36, 70.78it/s]

features:  64%|██████▍   | 12155/18966 [03:03<02:09, 52.66it/s]

features:  64%|██████▍   | 12175/18966 [03:03<02:06, 53.70it/s]

features:  65%|██████▍   | 12243/18966 [03:03<01:14, 89.92it/s]

features:  65%|██████▍   | 12274/18966 [03:04<01:34, 70.70it/s]

features:  65%|██████▍   | 12320/18966 [03:04<01:09, 95.72it/s]

features:  66%|██████▌   | 12432/18966 [03:04<00:35, 184.70it/s]

features:  66%|██████▌   | 12525/18966 [03:04<00:24, 265.68it/s]

features:  67%|██████▋   | 12629/18966 [03:04<00:17, 370.68it/s]

features:  67%|██████▋   | 12705/18966 [03:04<00:16, 369.89it/s]

features:  67%|██████▋   | 12770/18966 [03:05<00:15, 395.80it/s]

features:  68%|██████▊   | 12830/18966 [03:05<00:17, 345.78it/s]

features:  68%|██████▊   | 12919/18966 [03:05<00:14, 416.65it/s]

features:  69%|██████▊   | 12993/18966 [03:05<00:14, 406.98it/s]

features:  69%|██████▉   | 13043/18966 [03:06<00:24, 237.63it/s]

features:  69%|██████▉   | 13122/18966 [03:06<00:26, 223.80it/s]

features:  69%|██████▉   | 13172/18966 [03:06<00:26, 217.78it/s]

features:  70%|██████▉   | 13232/18966 [03:06<00:21, 263.84it/s]

features:  70%|███████   | 13288/18966 [03:07<00:21, 261.24it/s]

features:  70%|███████   | 13339/18966 [03:07<00:26, 211.19it/s]

features:  71%|███████   | 13393/18966 [03:07<00:21, 254.84it/s]

features:  71%|███████▏  | 13525/18966 [03:07<00:14, 384.50it/s]

features:  72%|███████▏  | 13574/18966 [03:08<00:18, 290.00it/s]

features:  72%|███████▏  | 13615/18966 [03:08<00:22, 241.83it/s]

features:  72%|███████▏  | 13647/18966 [03:08<00:23, 223.05it/s]

features:  72%|███████▏  | 13733/18966 [03:08<00:17, 301.20it/s]

features:  73%|███████▎  | 13823/18966 [03:08<00:12, 399.21it/s]

features:  74%|███████▎  | 13983/18966 [03:08<00:08, 596.40it/s]

features:  74%|███████▍  | 14061/18966 [03:09<00:08, 569.67it/s]

features:  74%|███████▍  | 14127/18966 [03:09<00:09, 504.24it/s]

features:  75%|███████▍  | 14197/18966 [03:09<00:15, 312.91it/s]

features:  76%|███████▌  | 14396/18966 [03:09<00:08, 551.05it/s]

features:  76%|███████▋  | 14485/18966 [03:10<00:08, 503.25it/s]

features:  77%|███████▋  | 14559/18966 [03:10<00:14, 306.71it/s]

features:  78%|███████▊  | 14728/18966 [03:10<00:10, 386.51it/s]

features:  78%|███████▊  | 14785/18966 [03:10<00:10, 403.31it/s]

features:  78%|███████▊  | 14863/18966 [03:11<00:08, 456.38it/s]

features:  79%|███████▉  | 15021/18966 [03:11<00:08, 491.36it/s]

features:  80%|███████▉  | 15117/18966 [03:11<00:06, 564.86it/s]

features:  80%|████████  | 15188/18966 [03:11<00:09, 414.65it/s]

features:  81%|████████  | 15272/18966 [03:11<00:07, 480.52it/s]

features:  81%|████████  | 15344/18966 [03:12<00:09, 377.46it/s]

features:  81%|████████▏ | 15439/18966 [03:12<00:07, 454.43it/s]

features:  82%|████████▏ | 15567/18966 [03:12<00:09, 362.85it/s]

features:  83%|████████▎ | 15688/18966 [03:12<00:07, 427.27it/s]

features:  83%|████████▎ | 15743/18966 [03:13<00:07, 423.35it/s]

features:  84%|████████▎ | 15866/18966 [03:13<00:05, 532.08it/s]

features:  84%|████████▍ | 16023/18966 [03:13<00:04, 723.38it/s]

features:  85%|████████▍ | 16119/18966 [03:13<00:03, 772.43it/s]

features:  86%|████████▌ | 16266/18966 [03:13<00:03, 763.71it/s]

features:  86%|████████▋ | 16380/18966 [03:13<00:04, 636.31it/s]

features:  87%|████████▋ | 16579/18966 [03:14<00:03, 788.11it/s]

features:  88%|████████▊ | 16667/18966 [03:14<00:05, 439.65it/s]

features:  88%|████████▊ | 16734/18966 [03:14<00:05, 420.31it/s]

features:  89%|████████▊ | 16822/18966 [03:14<00:04, 471.27it/s]

features:  89%|████████▉ | 16899/18966 [03:15<00:07, 271.72it/s]

features:  89%|████████▉ | 16946/18966 [03:16<00:12, 160.62it/s]

features:  90%|████████▉ | 16981/18966 [03:16<00:12, 163.13it/s]

features:  90%|████████▉ | 17011/18966 [03:16<00:12, 162.05it/s]

features:  90%|████████▉ | 17037/18966 [03:17<00:13, 144.33it/s]

features:  90%|█████████ | 17116/18966 [03:17<00:08, 219.47it/s]

features:  91%|█████████ | 17172/18966 [03:17<00:10, 178.48it/s]

features:  91%|█████████ | 17220/18966 [03:17<00:08, 210.82it/s]

features:  91%|█████████ | 17267/18966 [03:18<00:11, 149.40it/s]

features:  91%|█████████ | 17306/18966 [03:18<00:09, 169.97it/s]

features:  91%|█████████▏| 17351/18966 [03:18<00:07, 206.87it/s]

features:  92%|█████████▏| 17384/18966 [03:18<00:10, 154.10it/s]

features:  92%|█████████▏| 17527/18966 [03:19<00:04, 324.48it/s]

features:  93%|█████████▎| 17588/18966 [03:19<00:05, 243.53it/s]

features:  93%|█████████▎| 17635/18966 [03:19<00:04, 269.15it/s]

features:  94%|█████████▎| 17762/18966 [03:19<00:03, 374.72it/s]

features:  94%|█████████▍| 17815/18966 [03:19<00:03, 352.57it/s]

features:  94%|█████████▍| 17910/18966 [03:20<00:02, 413.96it/s]

features:  95%|█████████▍| 17960/18966 [03:20<00:04, 205.76it/s]

features:  95%|█████████▍| 17997/18966 [03:21<00:05, 174.36it/s]

features:  95%|█████████▌| 18027/18966 [03:21<00:07, 121.00it/s]

features:  95%|█████████▌| 18049/18966 [03:22<00:09, 98.83it/s] 

features:  95%|█████████▌| 18072/18966 [03:22<00:08, 110.15it/s]

features:  96%|█████████▌| 18141/18966 [03:22<00:04, 166.09it/s]

features:  96%|█████████▌| 18224/18966 [03:22<00:03, 222.59it/s]

features:  96%|█████████▋| 18255/18966 [03:22<00:03, 197.32it/s]

features:  96%|█████████▋| 18281/18966 [03:23<00:03, 204.89it/s]

features:  97%|█████████▋| 18333/18966 [03:23<00:02, 221.53it/s]

features:  97%|█████████▋| 18421/18966 [03:23<00:03, 176.28it/s]

features:  97%|█████████▋| 18465/18966 [03:24<00:02, 188.69it/s]

features:  98%|█████████▊| 18494/18966 [03:24<00:02, 200.56it/s]

features:  98%|█████████▊| 18542/18966 [03:24<00:02, 166.78it/s]

features:  98%|█████████▊| 18563/18966 [03:24<00:03, 115.18it/s]

features:  98%|█████████▊| 18611/18966 [03:25<00:02, 155.45it/s]

features:  99%|█████████▊| 18696/18966 [03:25<00:01, 240.71it/s]

features:  99%|█████████▉| 18733/18966 [03:25<00:01, 223.13it/s]

features:  99%|█████████▉| 18871/18966 [03:25<00:00, 295.09it/s]

features: 100%|██████████| 18966/18966 [03:25<00:00, 92.14it/s] 

Feature matrix: (18966, 174)  NaN=0  Inf=0


In [13]:
# -- Train/val/test split + StandardScaler (fit on normal train only) ---------
splits = df['split'].values
X_train_full, y_train_full = X_all[splits=='train'], y_all[splits=='train']
X_val,         y_val        = X_all[splits=='val'],   y_all[splits=='val']
X_test,        y_test       = X_all[splits=='test'],  y_all[splits=='test']

scaler = StandardScaler()
X_train_normal_raw = X_train_full[y_train_full == 0]
scaler.fit(X_train_normal_raw)

X_train = scaler.transform(X_train_full)
X_val   = scaler.transform(X_val)
X_test  = scaler.transform(X_test)
X_train_normal = X_train[y_train_full == 0]

print(f'Train: {X_train.shape}  attack_rate={y_train_full.mean():.3f}')
print(f'Val:   {X_val.shape}   attack_rate={y_val.mean():.3f}')
print(f'Test:  {X_test.shape}  attack_rate={y_test.mean():.3f}')
print(f'Train normal (for unsupervised training): {X_train_normal.shape}')


Train: (14843, 174)  attack_rate=0.630
Val:   (1812, 174)   attack_rate=0.622
Test:  (2311, 174)  attack_rate=0.707
Train normal (for unsupervised training): (5487, 174)


In [14]:
# -- Mutual information feature importance ------------------------------------
print('Computing mutual information...')
mi = mutual_info_classif(X_train, y_train_full, discrete_features=False, random_state=42)
feat_names = (
    [f'freq_{id_to_name(t)}' for t in TOP_IDS] +
    [f'disc_{id_to_name(t)}' for t in DISC_IDS] +
    ['stat_log_len','stat_log_unique','stat_diversity','stat_entropy',
     'stat_log_count','stat_log_size','stat_mean_id','stat_std_id'] +
    [f'bg_{id_to_name(a)}->{id_to_name(b)}' for a, b in TOP_BIGRAMS] +
    [f'ver_{v}' for v in ver_cols]
)
mi_series = pd.Series(mi, index=feat_names).sort_values(ascending=False)

fig, ax = plt.subplots(figsize=(12, 8))
top30 = mi_series.head(30)
ax.barh(top30.index[::-1], top30.values[::-1], color='#4C72B0', alpha=0.85)
ax.set_title('Top-30 Features by Mutual Information (vs attack label)', fontsize=13)
ax.set_xlabel('Mutual Information Score')
plt.tight_layout(); plt.savefig(f'{OUT}/fe_feature_importance.png', dpi=150); plt.show()

print('\nTop-20 most informative features:')
for name, score in top30.head(20).items():
    print(f'  {score:.4f}  {name}')

group_slices, start = {}, 0
for gname, gdim in feature_groups.items():
    group_slices[gname] = (start, start + gdim); start += gdim
print('\nMean MI per feature group:')
for gname, (s, e) in group_slices.items():
    print(f'  {gname:15s}  mean={mi[s:e].mean():.4f}  max={mi[s:e].max():.4f}')


Computing mutual information...



Top-20 most informative features:
  0.6526  disc_execve
  0.6512  freq_execve
  0.5738  ver_5.12
  0.4955  stat_log_size
  0.4954  disc_execve
  0.4912  freq_execve
  0.4623  stat_std_id
  0.4550  stat_mean_id
  0.4518  stat_entropy
  0.4380  freq_newfstatat
  0.4297  freq_brk
  0.4164  stat_diversity
  0.3835  freq_mprotect
  0.3822  freq_pread64
  0.3793  freq_access
  0.3769  freq_mmap
  0.3736  stat_log_count
  0.3713  stat_log_len
  0.3586  freq_munmap
  0.3553  freq_read

Mean MI per feature group:
  freq_60          mean=0.1629  max=0.6512
  disc_40          mean=0.0984  max=0.6526
  stats_8          mean=0.3956  max=0.4955
  bigram_40        mean=0.0414  max=0.3451
  ver_onehot       mean=0.0322  max=0.5738


## 5. Isolation Forest

**Key design choice:** Train on **normal sequences only** (unsupervised anomaly detection).
Attack sequences are seen only at evaluation time.

Isolation Forest partitions the feature space with random trees. Normal sequences need many
splits to isolate; attacks are isolated quickly (shorter paths → higher anomaly score).


In [15]:
import time
t0 = time.time()
iso = IsolationForest(
    n_estimators=300,
    contamination='auto',   # normal-only training → no need to specify contamination
    max_samples='auto',
    random_state=42,
    n_jobs=-1,
)
iso.fit(X_train_normal)
print(f'Isolation Forest trained in {time.time()-t0:.1f}s on {X_train_normal.shape[0]} normal sequences')


Isolation Forest trained in 0.2s on 5487 normal sequences


In [16]:
def evaluate_model(name, y_true, scores, threshold=None):
    """Evaluate anomaly scores; threshold auto-chosen on val set via Youden-J."""
    auc = roc_auc_score(y_true, scores)
    ap  = average_precision_score(y_true, scores)
    if threshold is None:
        fpr_c, tpr_c, threshs = roc_curve(y_true, scores)
        j = np.argmax(tpr_c - fpr_c)
        threshold = threshs[j]
    preds = (scores >= threshold).astype(int)
    cm    = confusion_matrix(y_true, preds)
    rep   = classification_report(y_true, preds, target_names=['Normal','Attack'], output_dict=True)
    print(f'[{name}]  AUC={auc:.4f}  AP={ap:.4f}  threshold={threshold:.4f}')
    print(classification_report(y_true, preds, target_names=['Normal','Attack']))
    return dict(auc=auc, ap=ap, threshold=threshold,
                f1=rep['Attack']['f1-score'],
                precision=rep['Attack']['precision'],
                recall=rep['Attack']['recall'],
                cm=cm)

if_scores_val  = -iso.decision_function(X_val)
if_scores_test = -iso.decision_function(X_test)

print('--- Validation ---')
if_val = evaluate_model('IF val', y_val, if_scores_val)
print('--- Test ---')
if_test = evaluate_model('IF test', y_test, if_scores_test, threshold=if_val['threshold'])


--- Validation ---
[IF val]  AUC=0.8474  AP=0.9007  threshold=-0.1158
              precision    recall  f1-score   support

      Normal       0.94      0.61      0.74       685
      Attack       0.81      0.98      0.88      1127

    accuracy                           0.84      1812
   macro avg       0.88      0.80      0.81      1812
weighted avg       0.86      0.84      0.83      1812

--- Test ---
[IF test]  AUC=0.8824  AP=0.9488  threshold=-0.1158
              precision    recall  f1-score   support

      Normal       0.97      0.57      0.72       678
      Attack       0.85      0.99      0.92      1633

    accuracy                           0.87      2311
   macro avg       0.91      0.78      0.82      2311
weighted avg       0.89      0.87      0.86      2311



In [17]:
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Confusion matrix
sns.heatmap(if_test['cm'], annot=True, fmt='d', ax=axes[0],
            xticklabels=['Normal','Attack'], yticklabels=['Normal','Attack'],
            cmap='Blues', linewidths=0.5)
axes[0].set_title('IF — Confusion Matrix (test)'); axes[0].set_ylabel('True'); axes[0].set_xlabel('Pred')

# ROC
fpr_if, tpr_if, _ = roc_curve(y_test, if_scores_test)
axes[1].plot(fpr_if, tpr_if, color='#4C72B0', lw=2, label=f'AUC={if_test["auc"]:.4f}')
axes[1].plot([0,1],[0,1],'k--',alpha=0.4); axes[1].set_title('IF — ROC Curve')
axes[1].set_xlabel('FPR'); axes[1].set_ylabel('TPR'); axes[1].legend()

# Score distribution
axes[2].hist(if_scores_test[y_test==0], bins=60, color='#4C72B0', alpha=0.7, label='Normal', density=True)
axes[2].hist(if_scores_test[y_test==1], bins=60, color='#DD8452', alpha=0.7, label='Attack',  density=True)
axes[2].axvline(if_val['threshold'], color='k', linestyle='--', label='threshold')
axes[2].set_title('IF — Score Distribution'); axes[2].legend()

plt.suptitle('Isolation Forest Results (test set)', fontsize=13)
plt.tight_layout(); plt.savefig(f'{OUT}/if_results.png', dpi=150); plt.show()


## 6. Variational Autoencoder (VAE)

**Architecture:** Input(174) → Dense(128,SELU) → Dropout(0.2) → Dense(64,SELU) → Dropout(0.2) → [μ, σ](24)
→ reparameterize → Dense(64,SELU) → Dropout(0.2) → Dense(128,SELU) → Dropout(0.2) → Output(174)

Loss: **ELBO = Reconstruction(MSE) + KL-divergence**

Trained on **normal sequences only**. At inference, attack sequences produce high
reconstruction error because the latent space was never shaped for them.

> Implementation uses a manual training loop for TF 2.21 / Keras 3 compatibility.


In [18]:
LATENT = 24
EPOCHS = 60
BATCH  = 256
INPUT_DIM = X_train.shape[1]

def build_encoder(input_dim, latent_dim):
    inp = keras.Input(shape=(input_dim,))
    x   = layers.Dense(128, activation='selu')(inp)
    x   = layers.Dropout(0.2)(x)
    x   = layers.Dense(64,  activation='selu')(x)
    x   = layers.Dropout(0.2)(x)
    mu  = layers.Dense(latent_dim)(x)
    lv  = layers.Dense(latent_dim)(x)
    return keras.Model(inp, [mu, lv], name='encoder')

def build_decoder(latent_dim, output_dim):
    inp = keras.Input(shape=(latent_dim,))
    x   = layers.Dense(64,  activation='selu')(inp)
    x   = layers.Dropout(0.2)(x)
    x   = layers.Dense(128, activation='selu')(x)
    x   = layers.Dropout(0.2)(x)
    out = layers.Dense(output_dim)(x)
    return keras.Model(inp, out, name='decoder')

def reparameterize(mu, lv):
    return mu + tf.exp(0.5 * lv) * tf.random.normal(tf.shape(mu))

def vae_step(enc, dec, opt, x_batch, training=True):
    with tf.GradientTape() as tape:
        mu, lv = enc(x_batch, training=training)
        lv     = tf.clip_by_value(lv, -8, 8)          # prevent exp overflow
        z      = reparameterize(mu, lv)
        x_hat  = dec(z, training=training)
        recon  = tf.reduce_mean(tf.reduce_sum(tf.square(x_batch - x_hat), axis=1))
        kl     = -0.5 * tf.reduce_mean(
                     tf.reduce_sum(1 + lv - tf.square(mu) - tf.exp(lv), axis=1))
        loss   = recon + kl
    if training:
        grads = tape.gradient(loss, enc.trainable_variables + dec.trainable_variables)
        opt.apply_gradients(zip(grads, enc.trainable_variables + dec.trainable_variables))
    return loss

def recon_error(enc, dec, x, n_samples=5):
    """Average reconstruction error over multiple samples to reduce variance."""
    errors = []
    for _ in range(n_samples):
        mu, lv = enc(x, training=False)
        lv     = tf.clip_by_value(lv, -8, 8)
        z      = reparameterize(mu, lv)
        x_hat  = dec(z, training=False)
        errors.append(tf.reduce_sum(tf.square(x - x_hat), axis=1).numpy())
    arr = np.mean(errors, axis=0)
    return np.nan_to_num(arr, nan=1e6, posinf=1e6, neginf=0.0)

encoder = build_encoder(INPUT_DIM, LATENT)
decoder = build_decoder(LATENT, INPUT_DIM)
encoder.summary()
decoder.summary()


Model: "encoder"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 174)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 128)       │     22,400 │ input_layer[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 128)       │          0 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 64)        │      8,256 │ dropout[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 64)        │          0 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 24)        │      1,560 │ dropout_1[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 24)        │      1,560 │ dropout_1[0][0]   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 33,776 (131.94 KB)

 Trainable params: 33,776 (131.94 KB)

 Non-trainable params: 0 (0.00 B)

Model: "decoder"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 24)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 64)             │         1,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 128)            │         8,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 174)            │        22,446 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 32,366 (126.43 KB)

 Trainable params: 32,366 (126.43 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
opt = keras.optimizers.Adam(1e-3)

n_val_vae  = int(len(X_train_normal) * 0.1)
X_vae_tr   = tf.constant(X_train_normal[n_val_vae:], dtype=tf.float32)
X_vae_val  = tf.constant(X_train_normal[:n_val_vae], dtype=tf.float32)

print(f'VAE training on {len(X_vae_tr)} normal seqs, validating on {len(X_vae_val)}')

train_losses, val_losses = [], []
best_val, best_enc_w, best_dec_w, patience_cnt = np.inf, None, None, 0
PATIENCE = 8

t0 = time.time()
for epoch in range(EPOCHS):
    idx = np.random.permutation(len(X_vae_tr))
    X_sh = tf.gather(X_vae_tr, idx)
    ep = []
    for i in range(0, len(X_sh), BATCH):
        ep.append(float(vae_step(encoder, decoder, opt, X_sh[i:i+BATCH], training=True)))
    vl = float(vae_step(encoder, decoder, opt, X_vae_val, training=False))
    train_losses.append(np.mean(ep)); val_losses.append(vl)
    if (epoch+1) % 10 == 0:
        print(f'  Epoch {epoch+1:3d}/{EPOCHS}  train={train_losses[-1]:.2f}  val={vl:.2f}')
    if vl < best_val:
        best_val = vl; best_enc_w = encoder.get_weights(); best_dec_w = decoder.get_weights()
        patience_cnt = 0
    else:
        patience_cnt += 1
        if patience_cnt >= PATIENCE:
            print(f'  Early stopping at epoch {epoch+1}'); break

encoder.set_weights(best_enc_w); decoder.set_weights(best_dec_w)
print(f'Trained {len(train_losses)} epochs in {time.time()-t0:.1f}s  best_val={best_val:.2f}')

# Training curves
fig, ax = plt.subplots(figsize=(9, 4))
ax.plot(train_losses, label='train_loss'); ax.plot(val_losses, label='val_loss')
ax.set_xlabel('Epoch'); ax.set_ylabel('ELBO Loss'); ax.set_title('VAE Training — DongTing')
ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout(); plt.savefig(f'{OUT}/vae_loss.png', dpi=150); plt.show()


VAE training on 4939 normal seqs, validating on 548


  Epoch  10/60  train=121.17  val=111.53


  Epoch  20/60  train=107.18  val=103.27


  Epoch  30/60  train=102.72  val=99.36


  Epoch  40/60  train=96.98  val=96.84


  Epoch  50/60  train=93.73  val=94.48


  Epoch  60/60  train=90.66  val=91.74
Trained 60 epochs in 35.5s  best_val=91.74


In [20]:
vae_scores_val  = recon_error(encoder, decoder, X_val.astype(np.float32))
vae_scores_test = recon_error(encoder, decoder, X_test.astype(np.float32))

print('--- Validation ---')
vae_val = evaluate_model('VAE val', y_val, vae_scores_val)
print('--- Test ---')
vae_test = evaluate_model('VAE test', y_test, vae_scores_test, threshold=vae_val['threshold'])


--- Validation ---
[VAE val]  AUC=0.9948  AP=0.9962  threshold=311.3642
              precision    recall  f1-score   support

      Normal       1.00      0.98      0.99       685
      Attack       0.99      1.00      0.99      1127

    accuracy                           0.99      1812
   macro avg       0.99      0.99      0.99      1812
weighted avg       0.99      0.99      0.99      1812

--- Test ---


[VAE test]  AUC=0.9954  AP=0.9956  threshold=311.3642
              precision    recall  f1-score   support

      Normal       1.00      0.98      0.99       678
      Attack       0.99      1.00      1.00      1633

    accuracy                           0.99      2311
   macro avg       0.99      0.99      0.99      2311
weighted avg       0.99      0.99      0.99      2311



In [21]:
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

sns.heatmap(vae_test['cm'], annot=True, fmt='d', ax=axes[0],
            xticklabels=['Normal','Attack'], yticklabels=['Normal','Attack'],
            cmap='Oranges', linewidths=0.5)
axes[0].set_title('VAE — Confusion Matrix (test)'); axes[0].set_ylabel('True'); axes[0].set_xlabel('Pred')

fpr_v, tpr_v, _ = roc_curve(y_test, vae_scores_test)
axes[1].plot(fpr_v, tpr_v, color='#DD8452', lw=2, label=f'AUC={vae_test["auc"]:.4f}')
axes[1].plot([0,1],[0,1],'k--',alpha=0.4); axes[1].set_title('VAE — ROC Curve')
axes[1].set_xlabel('FPR'); axes[1].set_ylabel('TPR'); axes[1].legend()

axes[2].hist(vae_scores_test[y_test==0], bins=60, color='#4C72B0', alpha=0.7, label='Normal', density=True)
axes[2].hist(vae_scores_test[y_test==1], bins=60, color='#DD8452', alpha=0.7, label='Attack',  density=True)
axes[2].axvline(vae_val['threshold'], color='k', linestyle='--', label='threshold')
axes[2].set_title('VAE — Score Distribution'); axes[2].legend()

plt.suptitle('VAE Results (test set)', fontsize=13)
plt.tight_layout(); plt.savefig(f'{OUT}/vae_results.png', dpi=150); plt.show()


In [22]:
# Latent space PCA visualization
mu_test, _ = encoder(X_test.astype(np.float32), training=False)
z_2d = PCA(n_components=2, random_state=42).fit_transform(mu_test.numpy())

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
for ax, labels, title in [
    (axes[0], y_test, 'True Labels'),
    (axes[1], (vae_scores_test >= vae_val['threshold']).astype(int), 'VAE Predictions'),
]:
    sc = ax.scatter(z_2d[:,0], z_2d[:,1], c=labels, cmap='coolwarm', s=4, alpha=0.4)
    ax.set_title(f'Latent Space (μ) — {title}'); ax.set_xlabel('PC1'); ax.set_ylabel('PC2')
    plt.colorbar(sc, ax=ax, label='0=Normal 1=Attack')
plt.tight_layout(); plt.savefig(f'{OUT}/vae_latent.png', dpi=150); plt.show()


## 7. Ensemble — α·VAE + (1-α)·IF

Per the DeSFAM paper (Section IV-D), scores are min-max normalized then combined:
**A(W) = α · A_VAE + (1-α) · A_IF**  with α = 0.7


In [23]:
ALPHA = 0.7

class MinMaxScaler:
    """Fit normalizer on reference scores, apply consistently to other splits."""
    def __init__(self, ref):
        self.lo = float(ref.min()); self.hi = float(ref.max())
    def __call__(self, x):
        return np.clip((x - self.lo) / (self.hi - self.lo + 1e-9), 0.0, 1.0)

# Compute training scores to fit normalizers
if_scores_train  = -iso.decision_function(X_train)
vae_scores_train = recon_error(encoder, decoder, X_train.astype(np.float32))

norm_if  = MinMaxScaler(if_scores_train)
norm_vae = MinMaxScaler(vae_scores_train)

ens_scores_val  = ALPHA * norm_vae(vae_scores_val)  + (1-ALPHA) * norm_if(if_scores_val)
ens_scores_test = ALPHA * norm_vae(vae_scores_test) + (1-ALPHA) * norm_if(if_scores_test)

print('--- Validation ---')
ens_val = evaluate_model('Ensemble val', y_val, ens_scores_val)
print('--- Test ---')
ens_test = evaluate_model('Ensemble test', y_test, ens_scores_test, threshold=ens_val['threshold'])


--- Validation ---
[Ensemble val]  AUC=0.8529  AP=0.9024  threshold=0.0476
              precision    recall  f1-score   support

      Normal       0.94      0.61      0.74       685
      Attack       0.81      0.98      0.88      1127

    accuracy                           0.84      1812
   macro avg       0.88      0.80      0.81      1812
weighted avg       0.86      0.84      0.83      1812

--- Test ---
[Ensemble test]  AUC=0.8848  AP=0.9485  threshold=0.0476
              precision    recall  f1-score   support

      Normal       0.97      0.57      0.72       678
      Attack       0.85      0.99      0.92      1633

    accuracy                           0.87      2311
   macro avg       0.91      0.78      0.82      2311
weighted avg       0.89      0.87      0.86      2311



## 8. Results Comparison

In [24]:
# ROC curves
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
for scores, label, clr in [
    (if_scores_test,  f'Isolation Forest (AUC={if_test["auc"]:.4f})',  '#4C72B0'),
    (vae_scores_test, f'VAE             (AUC={vae_test["auc"]:.4f})',  '#DD8452'),
    (ens_scores_test, f'Ensemble        (AUC={ens_test["auc"]:.4f})',  '#2ca02c'),
]:
    fpr_, tpr_, _ = roc_curve(y_test, scores)
    axes[0].plot(fpr_, tpr_, label=label, lw=2)
axes[0].plot([0,1],[0,1],'k--',alpha=0.4); axes[0].legend(fontsize=9)
axes[0].set_title('ROC Curves — Test Set'); axes[0].set_xlabel('FPR'); axes[0].set_ylabel('TPR')

# Score distributions
for ax, scores, thresh, title in [
    (axes[1], norm_vae(vae_scores_test), norm_vae(np.array([vae_val['threshold']]))[0], 'VAE Normalized Scores'),
]:
    ax.hist(scores[y_test==0], bins=60, color='#4C72B0', alpha=0.7, label='Normal', density=True)
    ax.hist(scores[y_test==1], bins=60, color='#DD8452', alpha=0.7, label='Attack',  density=True)
    ax.set_title(title); ax.legend()

plt.suptitle('Model Comparison — DongTing Test Set (174-dim FE)', fontsize=13)
plt.tight_layout(); plt.savefig(f'{OUT}/comparison_roc.png', dpi=150); plt.show()


In [25]:
# Summary table
rows = []
for mname, mres in [
    ('Isolation Forest', if_test),
    ('VAE',              vae_test),
    (f'Ensemble α={ALPHA}', ens_test),
]:
    rows.append({
        'Model':     mname,
        'ROC-AUC':   round(mres['auc'], 4),
        'Avg Prec':  round(mres['ap'], 4),
        'F1 (Attack)': round(mres['f1'], 4),
        'Precision': round(mres['precision'], 4),
        'Recall':    round(mres['recall'], 4),
    })
df_summary = pd.DataFrame(rows).set_index('Model')
print('=== Final Results — DongTing Test Set (174-dim features) ===')
print(df_summary.to_string())
df_summary.to_csv(f'{OUT}/summary_fe.csv')
print('\nSaved to outputs/summary_fe.csv')


=== Final Results — DongTing Test Set (174-dim features) ===
                  ROC-AUC  Avg Prec  F1 (Attack)  Precision  Recall
Model                                                              
Isolation Forest   0.8824    0.9488       0.9151     0.8480  0.9939
VAE                0.9954    0.9956       0.9954     0.9915  0.9994
Ensemble α=0.7     0.8848    0.9485       0.9151     0.8480  0.9939

Saved to outputs/summary_fe.csv


In [26]:
# Bar chart
metric_cols = ['ROC-AUC', 'F1 (Attack)', 'Precision', 'Recall']
x = np.arange(len(metric_cols)); width = 0.25
fig, ax = plt.subplots(figsize=(12, 5))
for i, (model, clr) in enumerate(zip(df_summary.index, ['#4C72B0','#DD8452','#2ca02c'])):
    bars = ax.bar(x + i*width, df_summary.loc[model, metric_cols], width,
                  label=model, color=clr, alpha=0.85)
    for bar in bars:
        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.005,
                f'{bar.get_height():.3f}', ha='center', va='bottom', fontsize=8)
ax.set_xticks(x + width); ax.set_xticklabels(metric_cols)
ax.set_ylim(0, 1.15); ax.legend(); ax.grid(axis='y', alpha=0.3)
ax.set_title('Metric Comparison — IF vs VAE vs Ensemble (DongTing 174-dim)', fontsize=13)
plt.tight_layout(); plt.savefig(f'{OUT}/comparison_bar.png', dpi=150); plt.show()


## 10. PyOD Model Suite — Comprehensive Comparison

[`pyod`](https://github.com/yzhao062/pyod) provides 50+ outlier-detection
algorithms with a uniform API. We train a representative slate on the same
`X_train_normal` data and evaluate on `(X_val, y_val)` and `(X_test, y_test)`
using the existing `evaluate_model` helper.

Algorithms covered:

| Category | Algorithm | Notes |
|---|---|---|
| Tree | `IForest` | PyOD wrapper of Isolation Forest |
| Probabilistic | `COPOD`, `ECOD` | Parameter-free, fast |
| Distribution | `HBOS` | Histogram-based, very fast |
| Linear | `PCA` | Reconstruction error in PCA basis |
| Proximity | `KNN`, `LOF` | Distance / density based |
| Kernel | `OCSVM` | One-class SVM (RBF, subsampled fit) |
| Deep | `AutoEncoder` | PyOD's torch AE — analogue to the VAE above |

All models are trained on **normal-only** data; thresholds are selected on the
validation set (Youden-J) and held fixed on the test set.


In [27]:
# Install pyod inside the container if not yet present.
import importlib, subprocess, sys
if importlib.util.find_spec('pyod') is None:
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '--quiet', 'pyod>=2.0'])
import pyod
print('pyod version:', pyod.__version__)


pyod version: 3.5.1


In [28]:
# -- Imports & model registry -------------------------------------------------
import time, warnings, traceback
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_curve, roc_auc_score, average_precision_score

from pyod.models.iforest      import IForest
from pyod.models.copod        import COPOD
from pyod.models.ecod         import ECOD
from pyod.models.hbos         import HBOS
from pyod.models.pca          import PCA  as PyodPCA
from pyod.models.knn          import KNN
from pyod.models.lof          import LOF
from pyod.models.ocsvm        import OCSVM

warnings.filterwarnings('ignore')

# AutoEncoder requires torch — guard the import so the rest still runs.
try:
    from pyod.models.auto_encoder import AutoEncoder
    HAS_AE = True
except Exception as e:
    print('AutoEncoder unavailable:', e)
    HAS_AE = False

RNG = 42
n_normal = X_train_normal.shape[0]
print(f'Training pool: {n_normal} normal sequences, {X_train_normal.shape[1]} features')


Training pool: 5487 normal sequences, 174 features


In [29]:
# -- Build model registry ----------------------------------------------------
# OCSVM / LOF can be O(n^2); cap their fit set so the cell finishes in minutes.
SUBSAMPLE_LIMIT = 5000
rng = np.random.default_rng(RNG)
idx_sub = rng.choice(n_normal, size=min(SUBSAMPLE_LIMIT, n_normal), replace=False)
X_train_normal_sub = X_train_normal[idx_sub]

models = {
    'IForest': (IForest(n_estimators=300, random_state=RNG, n_jobs=-1), X_train_normal),
    'COPOD':   (COPOD(),                                                  X_train_normal),
    'ECOD':    (ECOD(),                                                   X_train_normal),
    'HBOS':    (HBOS(n_bins=50),                                          X_train_normal),
    'PCA':     (PyodPCA(n_components=min(32, X_train_normal.shape[1]), random_state=RNG),
                                                                          X_train_normal),
    'KNN':     (KNN(n_neighbors=20, method='mean', n_jobs=-1),            X_train_normal_sub),
    'LOF':     (LOF(n_neighbors=20, n_jobs=-1),                           X_train_normal_sub),
    'OCSVM':   (OCSVM(kernel='rbf', gamma='scale', nu=0.1),               X_train_normal_sub),
}

if HAS_AE:
    models['AutoEncoder'] = (
        AutoEncoder(hidden_neuron_list=[64, 32], epoch_num=30, batch_size=256,
                    contamination=0.1, verbose=0),
        X_train_normal,
    )

print('Registered models:', list(models.keys()))
print(f'(KNN/LOF/OCSVM fit on {len(X_train_normal_sub)}-row subsample to bound runtime)')


Registered models: ['IForest', 'COPOD', 'ECOD', 'HBOS', 'PCA', 'KNN', 'LOF', 'OCSVM', 'AutoEncoder']
(KNN/LOF/OCSVM fit on 5000-row subsample to bound runtime)


In [30]:
# -- Train + score every model ------------------------------------------------
pyod_results = {}
pyod_scores  = {}   # name -> dict(train, val, test)

for name, (mdl, X_fit) in models.items():
    print(f'\n--- {name} ---')
    try:
        t0 = time.time()
        mdl.fit(X_fit)
        t_fit = time.time() - t0

        # decision_function: higher = more anomalous (pyod convention)
        sc_val  = mdl.decision_function(X_val)
        sc_test = mdl.decision_function(X_test)
        sc_train = mdl.decision_function(X_train)

        val_res  = evaluate_model(f'{name} val',  y_val,  sc_val)
        test_res = evaluate_model(f'{name} test', y_test, sc_test,
                                  threshold=val_res['threshold'])

        pyod_results[name] = {
            'fit_seconds': round(t_fit, 2),
            'val':  val_res,
            'test': test_res,
        }
        pyod_scores[name] = {'train': sc_train, 'val': sc_val, 'test': sc_test}
        print(f'  fit: {t_fit:.1f}s')
    except Exception as e:
        print(f'  FAILED: {e}')
        traceback.print_exc()



--- IForest ---


[IForest val]  AUC=0.8474  AP=0.9007  threshold=-0.0734
              precision    recall  f1-score   support

      Normal       0.94      0.61      0.74       685
      Attack       0.81      0.98      0.88      1127

    accuracy                           0.84      1812
   macro avg       0.88      0.80      0.81      1812
weighted avg       0.86      0.84      0.83      1812

[IForest test]  AUC=0.8824  AP=0.9488  threshold=-0.0734
              precision    recall  f1-score   support

      Normal       0.97      0.57      0.72       678
      Attack       0.85      0.99      0.92      1633

    accuracy                           0.87      2311
   macro avg       0.91      0.78      0.82      2311
weighted avg       0.89      0.87      0.86      2311

  fit: 0.4s

--- COPOD ---


[COPOD val]  AUC=0.8582  AP=0.8922  threshold=55.9157
              precision    recall  f1-score   support

      Normal       0.97      0.67      0.79       685
      Attack       0.83      0.99      0.90      1127

    accuracy                           0.87      1812
   macro avg       0.90      0.83      0.85      1812
weighted avg       0.89      0.87      0.86      1812

[COPOD test]  AUC=0.8194  AP=0.9037  threshold=55.9157
              precision    recall  f1-score   support

      Normal       0.71      0.62      0.66       678
      Attack       0.85      0.89      0.87      1633

    accuracy                           0.81      2311
   macro avg       0.78      0.76      0.77      2311
weighted avg       0.81      0.81      0.81      2311

  fit: 0.4s

--- ECOD ---


[ECOD val]  AUC=0.8636  AP=0.8989  threshold=68.0914
              precision    recall  f1-score   support

      Normal       0.99      0.68      0.81       685
      Attack       0.84      0.99      0.91      1127

    accuracy                           0.88      1812
   macro avg       0.91      0.84      0.86      1812
weighted avg       0.89      0.88      0.87      1812

[ECOD test]  AUC=0.8137  AP=0.9009  threshold=68.0914
              precision    recall  f1-score   support

      Normal       0.71      0.63      0.67       678
      Attack       0.85      0.89      0.87      1633

    accuracy                           0.82      2311
   macro avg       0.78      0.76      0.77      2311
weighted avg       0.81      0.82      0.81      2311

  fit: 0.1s

--- HBOS ---


[HBOS val]  AUC=0.6924  AP=0.7361  threshold=61.9290
              precision    recall  f1-score   support

      Normal       0.88      0.44      0.59       685
      Attack       0.74      0.96      0.84      1127

    accuracy                           0.77      1812
   macro avg       0.81      0.70      0.71      1812
weighted avg       0.79      0.77      0.74      1812

[HBOS test]  AUC=0.7453  AP=0.8363  threshold=61.9290
              precision    recall  f1-score   support

      Normal       0.91      0.43      0.59       678
      Attack       0.81      0.98      0.89      1633

    accuracy                           0.82      2311
   macro avg       0.86      0.71      0.74      2311
weighted avg       0.84      0.82      0.80      2311

  fit: 1.3s

--- PCA ---
[PCA val]  AUC=0.9933  AP=0.9953  threshold=41252.4391
              precision    recall  f1-score   support

      Normal       1.00      0.98      0.99       685
      Attack       0.99      1.00      0.99      1

[KNN val]  AUC=0.9855  AP=0.9912  threshold=17.4023
              precision    recall  f1-score   support

      Normal       0.86      0.99      0.92       685
      Attack       0.99      0.90      0.95      1127

    accuracy                           0.94      1812
   macro avg       0.93      0.95      0.93      1812
weighted avg       0.94      0.94      0.94      1812

[KNN test]  AUC=0.9934  AP=0.9952  threshold=17.4023
              precision    recall  f1-score   support

      Normal       0.95      0.99      0.97       678
      Attack       0.99      0.98      0.99      1633

    accuracy                           0.98      2311
   macro avg       0.97      0.98      0.98      2311
weighted avg       0.98      0.98      0.98      2311

  fit: 0.1s

--- LOF ---


[LOF val]  AUC=0.9097  AP=0.8921  threshold=2.2030
              precision    recall  f1-score   support

      Normal       0.97      0.82      0.89       685
      Attack       0.90      0.99      0.94      1127

    accuracy                           0.92      1812
   macro avg       0.94      0.90      0.92      1812
weighted avg       0.93      0.92      0.92      1812

[LOF test]  AUC=0.9185  AP=0.9113  threshold=2.2030
              precision    recall  f1-score   support

      Normal       0.93      0.83      0.88       678
      Attack       0.93      0.97      0.95      1633

    accuracy                           0.93      2311
   macro avg       0.93      0.90      0.91      2311
weighted avg       0.93      0.93      0.93      2311

  fit: 0.1s

--- OCSVM ---


[OCSVM val]  AUC=0.9905  AP=0.9940  threshold=0.2477
              precision    recall  f1-score   support

      Normal       1.00      0.93      0.96       685
      Attack       0.96      1.00      0.98      1127

    accuracy                           0.97      1812
   macro avg       0.98      0.96      0.97      1812
weighted avg       0.97      0.97      0.97      1812

[OCSVM test]  AUC=0.9952  AP=0.9972  threshold=0.2477
              precision    recall  f1-score   support

      Normal       1.00      0.92      0.96       678
      Attack       0.97      1.00      0.98      1633

    accuracy                           0.98      2311
   macro avg       0.98      0.96      0.97      2311
weighted avg       0.98      0.98      0.98      2311

  fit: 0.6s

--- AutoEncoder ---


[AutoEncoder val]  AUC=1.0000  AP=1.0000  threshold=141421344.0000
              precision    recall  f1-score   support

      Normal       1.00      1.00      1.00       685
      Attack       1.00      1.00      1.00      1127

    accuracy                           1.00      1812
   macro avg       1.00      1.00      1.00      1812
weighted avg       1.00      1.00      1.00      1812

[AutoEncoder test]  AUC=1.0000  AP=1.0000  threshold=141421344.0000
              precision    recall  f1-score   support

      Normal       1.00      1.00      1.00       678
      Attack       1.00      1.00      1.00      1633

    accuracy                           1.00      2311
   macro avg       1.00      1.00      1.00      2311
weighted avg       1.00      1.00      1.00      2311

  fit: 8.9s


In [31]:
# -- Summary table ------------------------------------------------------------
rows = []
for name, res in pyod_results.items():
    rows.append({
        'Model':       name,
        'Fit (s)':     res['fit_seconds'],
        'Val AUC':     round(res['val']['auc'], 4),
        'Test AUC':    round(res['test']['auc'], 4),
        'Avg Prec':    round(res['test']['ap'], 4),
        'F1 (Attack)': round(res['test']['f1'], 4),
        'Precision':   round(res['test']['precision'], 4),
        'Recall':      round(res['test']['recall'], 4),
    })
df_pyod = (pd.DataFrame(rows)
             .sort_values('Test AUC', ascending=False)
             .set_index('Model'))
print('=== PyOD Results — DongTing Test Set ===')
print(df_pyod.to_string())
df_pyod.to_csv(f'{OUT}/pyod_summary.csv')
print(f'\nSaved to {OUT}/pyod_summary.csv')


=== PyOD Results — DongTing Test Set ===
             Fit (s)  Val AUC  Test AUC  Avg Prec  F1 (Attack)  Precision  Recall
Model                                                                            
AutoEncoder     8.85   1.0000    1.0000    1.0000       1.0000     1.0000  1.0000
OCSVM           0.56   0.9905    0.9952    0.9972       0.9846     0.9697  1.0000
KNN             0.12   0.9855    0.9934    0.9952       0.9864     0.9944  0.9786
PCA             0.06   0.9933    0.9910    0.9940       0.9924     0.9849  1.0000
LOF             0.06   0.9097    0.9185    0.9113       0.9524     0.9315  0.9743
IForest         0.37   0.8474    0.8824    0.9488       0.9151     0.8480  0.9939
COPOD           0.42   0.8582    0.8194    0.9037       0.8716     0.8503  0.8941
ECOD            0.06   0.8636    0.8137    0.9009       0.8730     0.8524  0.8947
HBOS            1.25   0.6924    0.7453    0.8363       0.8859     0.8068  0.9822

Saved to outputs/pyod_summary.csv


In [32]:
# -- ROC curves for all PyOD models (+ existing IF / VAE / Ensemble) ----------
fig, ax = plt.subplots(figsize=(9, 7))
palette = plt.cm.tab10.colors

# Existing reference curves
for scores, label, clr in [
    (if_scores_test,  f'sklearn IF (AUC={if_test["auc"]:.3f})',   'black'),
    (vae_scores_test, f'VAE (AUC={vae_test["auc"]:.3f})',          'dimgray'),
    (ens_scores_test, f'Ensemble (AUC={ens_test["auc"]:.3f})',     'darkred'),
]:
    fpr, tpr, _ = roc_curve(y_test, scores)
    ax.plot(fpr, tpr, '--', lw=1.5, label=label, color=clr, alpha=0.8)

# PyOD models
for i, (name, sc) in enumerate(pyod_scores.items()):
    auc = pyod_results[name]['test']['auc']
    fpr, tpr, _ = roc_curve(y_test, sc['test'])
    ax.plot(fpr, tpr, lw=2, color=palette[i % len(palette)],
            label=f'{name} (AUC={auc:.3f})')

ax.plot([0, 1], [0, 1], 'k:', alpha=0.4)
ax.set_xlabel('False Positive Rate'); ax.set_ylabel('True Positive Rate')
ax.set_title('ROC Curves — PyOD Suite vs. Custom Pipeline (DongTing test)')
ax.legend(fontsize=8, loc='lower right'); ax.grid(alpha=0.3)
plt.tight_layout(); plt.savefig(f'{OUT}/pyod_roc.png', dpi=150); plt.show()


In [33]:
# -- Metric bar chart for PyOD models ----------------------------------------
metric_cols = ['Test AUC', 'F1 (Attack)', 'Precision', 'Recall']
fig, ax = plt.subplots(figsize=(14, 5))
x = np.arange(len(df_pyod))
width = 0.2
for j, m in enumerate(metric_cols):
    bars = ax.bar(x + j*width, df_pyod[m].values, width, label=m, alpha=0.85)
    for b in bars:
        ax.text(b.get_x()+b.get_width()/2, b.get_height()+0.005,
                f'{b.get_height():.2f}', ha='center', va='bottom', fontsize=7)
ax.set_xticks(x + 1.5*width); ax.set_xticklabels(df_pyod.index, rotation=30, ha='right')
ax.set_ylim(0, 1.15); ax.legend(loc='upper right'); ax.grid(axis='y', alpha=0.3)
ax.set_title('PyOD Suite — Per-Model Metrics (DongTing test)', fontsize=13)
plt.tight_layout(); plt.savefig(f'{OUT}/pyod_metrics.png', dpi=150); plt.show()


In [34]:
# -- Score-average ensemble across PyOD models -------------------------------
# Min-max normalize each model's *training* score distribution, then combine.
class _MM:
    def __init__(self, ref):
        self.lo = float(ref.min()); self.hi = float(ref.max())
    def __call__(self, x):
        return np.clip((x - self.lo) / (self.hi - self.lo + 1e-9), 0.0, 1.0)

# Use the top-K models by validation AUC to avoid dragging the average down.
TOP_K = min(4, len(pyod_results))
top_models = sorted(pyod_results.items(), key=lambda kv: kv[1]['val']['auc'],
                    reverse=True)[:TOP_K]
top_names = [n for n, _ in top_models]
print(f'Combining top-{TOP_K} by val AUC: {top_names}')

# NOTE: use distinct variable names to avoid shadowing the §7 Ensemble dicts
# (ens_val / ens_test), which are needed by §11 per-category eval.
norms = {n: _MM(pyod_scores[n]['train']) for n in top_names}
pyod_avg_val_scores  = np.mean([norms[n](pyod_scores[n]['val'])  for n in top_names], axis=0)
pyod_avg_test_scores = np.mean([norms[n](pyod_scores[n]['test']) for n in top_names], axis=0)

print('\n--- PyOD score-average ensemble ---')
pyod_ens_val  = evaluate_model('PyOD-Avg val',  y_val,  pyod_avg_val_scores)
pyod_ens_test = evaluate_model('PyOD-Avg test', y_test, pyod_avg_test_scores,
                               threshold=pyod_ens_val['threshold'])

Combining top-4 by val AUC: ['AutoEncoder', 'PCA', 'OCSVM', 'KNN']

--- PyOD score-average ensemble ---
[PyOD-Avg val]  AUC=0.9959  AP=0.9976  threshold=0.1597
              precision    recall  f1-score   support

      Normal       1.00      0.96      0.98       685
      Attack       0.97      1.00      0.99      1127

    accuracy                           0.98      1812
   macro avg       0.99      0.98      0.98      1812
weighted avg       0.98      0.98      0.98      1812

[PyOD-Avg test]  AUC=0.9988  AP=0.9995  threshold=0.1597
              precision    recall  f1-score   support

      Normal       1.00      0.94      0.97       678
      Attack       0.98      1.00      0.99      1633

    accuracy                           0.98      2311
   macro avg       0.99      0.97      0.98      2311
weighted avg       0.98      0.98      0.98      2311



In [35]:
# -- Persist PyOD report ------------------------------------------------------
import json as _json

def _clean(o):
    if isinstance(o, dict):  return {k: _clean(v) for k, v in o.items()}
    if isinstance(o, list):  return [_clean(v) for v in o]
    if isinstance(o, np.ndarray): return o.tolist()
    if isinstance(o, (np.floating, np.integer)): return o.item()
    return o

report = {
    'feature_dim': int(X_train.shape[1]),
    'n_train_normal': int(n_normal),
    'subsample_for_knn_lof_ocsvm': int(min(SUBSAMPLE_LIMIT, n_normal)),
    'models': _clean(pyod_results),
    'ensemble_top_k': {
        'members': top_names,
        'val':  _clean(pyod_ens_val),
        'test': _clean(pyod_ens_test),
    },
}
with open(f'{OUT}/pyod_report.json', 'w') as f:
    _json.dump(report, f, indent=2)
print(f'Wrote {OUT}/pyod_report.json')


Wrote outputs/pyod_report.json


## 11. Per-Bug-Category Test Evaluation

Findings from `dongting_eda.ipynb` show the attack class is **multi-modal**:
13 distinct bug categories (KASAN, WARNING, general_protection_fault,
memory_leak, …) form internal sub-clusters that don't necessarily share
syscall signatures.  Aggregate AUC hides whether a model handles every
sub-cluster well — a 95 % global recall could still mean *one* category is at
50 %.  Here we break down each trained model's test-set performance by
bug-category prefix.

We reuse:
- `df` (in scope from §2) — has `kcb_bug_name` for category parsing,
- `y_test` (§4) — test labels,
- `if_scores_test`, `vae_scores_test`, `ens_scores_test` (§5-7) — scores,
- `pyod_scores`, `pyod_results` (§10) — PyOD model scores + val thresholds,
- `evaluate_model` (§5) — eval helper.

No retraining; outputs land in `outputs/`.


In [36]:
# Local palette for the per-category section (modeling notebook has none defined).
PALETTE = {'Normal': '#4C72B0', 'Attack': '#DD8452'}

# -- Parse bug categories for test rows --------------------------------------
import re
from collections import Counter

PREFIX_RE = re.compile(
    r'^(KASAN|UBSAN|INFO|WARNING|BUG|general_protection_fault|'
    r'kernel_BUG|divide_error|memory_leak|inconsistent_lock_state|'
    r'possible_deadlock|unable_to_handle_kernel|stack_segment|'
    r'KCSAN|KMSAN|task_hung|softirq_pending|panic|task)')

def parse_category(label, bug_name):
    if label == 0:
        return 'Normal'
    m = PREFIX_RE.match(bug_name or '')
    return m.group(1) if m else 'other'

# df is still in scope and ordered the same way y_test was sliced (§4).
test_df = df.loc[df['split'] == 'test'].reset_index(drop=True).copy()
assert len(test_df) == len(y_test), (
    f'Length mismatch: test_df={len(test_df)} vs y_test={len(y_test)}')
assert (test_df['label'].values == y_test).all(), 'Label order drift'

test_df['category'] = [parse_category(l, b)
                       for l, b in zip(test_df['label'], test_df['kcb_bug_name'])]
cat_counts = test_df['category'].value_counts()
print('Test-set category distribution:')
print(cat_counts.to_string())
print(f'\nTotal test rows: {len(test_df)}  (attack={int((y_test==1).sum())}, '
      f'normal={int((y_test==0).sum())})')


Test-set category distribution:
category
Normal                      678
KASAN                       445
WARNING                     422
general_protection_fault    341
memory_leak                 241
KMSAN                        65
INFO                         53
BUG                          33
kernel_BUG                   19
possible_deadlock             9
divide_error                  2
inconsistent_lock_state       2
other                         1

Total test rows: 2311  (attack=1633, normal=678)


In [37]:
# -- Collect every trained model's TEST scores + val-tuned threshold ---------
# Existing pipeline:
model_scores = {
    'IsolationForest': (if_scores_test,  if_val['threshold']),
    'VAE':             (vae_scores_test, vae_val['threshold']),
    f'Ensemble α={ALPHA}': (ens_scores_test, ens_val['threshold']),
}

# PyOD suite (added in §10) — include top-4 by val AUC + the score-average ensemble.
top4 = sorted(pyod_results.items(), key=lambda kv: kv[1]['val']['auc'],
              reverse=True)[:4]
for name, res in top4:
    model_scores[f'PyOD-{name}'] = (
        pyod_scores[name]['test'],
        res['val']['threshold'],
    )

# PyOD top-K averaged ensemble (computed in §10 cell)
try:
    model_scores['PyOD-Avg'] = (pyod_avg_test_scores, pyod_ens_val['threshold'])
except NameError:
    pass

print('Models under per-category review:')
for n in model_scores: print(f'  - {n}')


Models under per-category review:
  - IsolationForest
  - VAE
  - Ensemble α=0.7
  - PyOD-AutoEncoder
  - PyOD-PCA
  - PyOD-OCSVM
  - PyOD-KNN
  - PyOD-Avg


In [38]:
# -- Per-category recall (attack categories) + Normal-FPR ---------------------
from sklearn.metrics import recall_score, precision_score

rows = []
for name, (scores, thr) in model_scores.items():
    preds = (scores >= thr).astype(int)
    for cat in cat_counts.index:
        sel = (test_df['category'] == cat).values
        n   = int(sel.sum())
        if n == 0: continue
        y_c = y_test[sel]; p_c = preds[sel]
        if cat == 'Normal':
            # For the Normal slice, "recall" is N/A; report False-Positive Rate
            fpr = float((p_c == 1).mean())
            rows.append({'model': name, 'category': cat, 'n': n,
                         'metric': 'FPR (lower=better)', 'value': fpr})
        else:
            # Attack category → recall = true-positive rate within this category
            rec = float((p_c == 1).mean())
            rows.append({'model': name, 'category': cat, 'n': n,
                         'metric': 'Recall',               'value': rec})

df_perc = pd.DataFrame(rows)
heat = (df_perc.pivot_table(index='category', columns='model', values='value'))
# Order rows: Normal first, then attacks by support desc
attack_cats = [c for c in cat_counts.index if c != 'Normal']
heat = heat.reindex(['Normal'] + attack_cats)
heat = heat[list(model_scores.keys())]

# Show table
print('Per-category test scores (recall for attack rows, FPR for Normal):')
display(heat.style.format('{:.3f}').background_gradient(cmap='RdYlGn', axis=None,
                                                       vmin=0, vmax=1)
        .set_caption('Green = good (high recall on attacks, low FPR on normals after color invert below)'))   if 'display' in dir() else print(heat.round(3).to_string())

heat.to_csv(f'{OUT}/per_category_metrics.csv')


Per-category test scores (recall for attack rows, FPR for Normal):
model                     IsolationForest    VAE  Ensemble α=0.7  PyOD-AutoEncoder  PyOD-PCA  PyOD-OCSVM  PyOD-KNN  PyOD-Avg
category                                                                                                                    
Normal                              0.429  0.021           0.429               0.0     0.037       0.075     0.013     0.056
KASAN                               0.998  1.000           0.998               1.0     1.000       1.000     0.944     1.000
WARNING                             0.995  0.998           0.995               1.0     1.000       1.000     0.986     1.000
general_protection_fault            0.997  1.000           0.997               1.0     1.000       1.000     1.000     1.000
memory_leak                         1.000  1.000           1.000               1.0     1.000       1.000     1.000     1.000
KMSAN                               1.000  1.000          

In [39]:
# -- Heatmap visualization --------------------------------------------------
# Two-panel: (a) recall on attack categories (higher=better),
#            (b) FPR on Normal slice (lower=better)
fig, axes = plt.subplots(2, 1, figsize=(13, max(6, 0.55*len(heat))),
                         gridspec_kw={'height_ratios': [len(attack_cats), 1]})

attack_heat = heat.loc[attack_cats]
sns.heatmap(attack_heat, annot=True, fmt='.2f', cmap='RdYlGn', vmin=0, vmax=1,
            cbar_kws={'label': 'Recall (higher = better)'},
            ax=axes[0], linewidths=0.4)
axes[0].set_title('Per-bug-category test recall')
axes[0].set_ylabel('Bug category'); axes[0].set_xlabel('')
# Append support to ytick labels
yticks = [f'{c}  (n={int(cat_counts[c])})' for c in attack_cats]
axes[0].set_yticklabels(yticks, rotation=0)

normal_row = heat.loc[['Normal']]
sns.heatmap(normal_row, annot=True, fmt='.3f', cmap='RdYlGn_r', vmin=0, vmax=0.2,
            cbar_kws={'label': 'False Positive Rate (lower = better)'},
            ax=axes[1], linewidths=0.4)
axes[1].set_title('Normal slice — false-positive rate')
axes[1].set_yticklabels([f'Normal  (n={int(cat_counts["Normal"])})'], rotation=0)
axes[1].set_xlabel('Model'); axes[1].set_ylabel('')

plt.tight_layout(); plt.savefig(f'{OUT}/per_category_heatmap.png', dpi=150); plt.show()


In [40]:
# -- Per-category score distributions for the two best models ----------------
# Pick best by overall test AUC
overall = []
for name, (scores, _) in model_scores.items():
    overall.append((name, roc_auc_score(y_test, scores)))
overall.sort(key=lambda x: x[1], reverse=True)
best_two = overall[:2]
print('Score-distribution focus models:', [n for n, _ in best_two])

# Subset to attack categories with at least 30 test samples to make plots readable
big_cats = [c for c in attack_cats if cat_counts[c] >= 30]
fig, axes = plt.subplots(len(best_two), 1, figsize=(14, 5*len(best_two)), sharex=False)
if len(best_two) == 1: axes = [axes]
for ax, (name, auc) in zip(axes, best_two):
    scores, thr = model_scores[name]
    # Normalize scores 0-1 for cross-model comparability
    s_norm = (scores - scores.min()) / (scores.max() - scores.min() + 1e-9)
    thr_norm = (thr - scores.min()) / (scores.max() - scores.min() + 1e-9)
    data = []
    labs = ['Normal'] + big_cats
    for cat in labs:
        sel = (test_df['category'] == cat).values
        data.append(s_norm[sel])
    parts = ax.violinplot(data, showmeans=False, showmedians=True)
    for i, b in enumerate(parts['bodies']):
        b.set_facecolor(PALETTE['Normal'] if labs[i]=='Normal' else PALETTE['Attack'])
        b.set_alpha(0.6)
    ax.axhline(thr_norm, color='red', linestyle='--', linewidth=1, label=f'val threshold')
    ax.set_xticks(range(1, len(labs)+1))
    ax.set_xticklabels([f'{l}\nn={int(cat_counts[l])}' for l in labs], rotation=30, ha='right')
    ax.set_ylabel('Normalized anomaly score')
    ax.set_title(f'{name}  —  test AUC = {auc:.3f}')
    ax.legend(loc='upper left'); ax.grid(axis='y', alpha=0.3)

plt.suptitle('Per-category test-score distributions (top-2 models)', y=1.005, fontsize=13)
plt.tight_layout(); plt.savefig(f'{OUT}/per_category_score_dist.png', dpi=150); plt.show()


Score-distribution focus models: ['PyOD-AutoEncoder', 'PyOD-Avg']


In [41]:
# -- Worst-category summary across models -----------------------------------
attack_recall = heat.loc[attack_cats]
worst_rows = []
for cat in attack_cats:
    row = attack_recall.loc[cat]
    worst_rows.append({
        'category': cat,
        'n':        int(cat_counts[cat]),
        'best_model':  row.idxmax(),
        'best_recall': round(row.max(), 3),
        'worst_model': row.idxmin(),
        'worst_recall': round(row.min(), 3),
        'spread':      round(row.max() - row.min(), 3),
    })
df_worst = (pd.DataFrame(worst_rows)
              .sort_values('worst_recall'))
print('=== Hardest categories by worst-case recall ===')
print(df_worst.to_string(index=False))
df_worst.to_csv(f'{OUT}/per_category_hardest.csv', index=False)

# Save report
report = {
    'test_size': int(len(test_df)),
    'categories': cat_counts.to_dict(),
    'overall_test_auc': {n: round(a, 4) for n, a in overall},
    'per_category_recall':  attack_recall.round(4).to_dict(),
    'normal_fpr':           heat.loc['Normal'].round(4).to_dict(),
    'hardest_categories':   df_worst.head(5).to_dict(orient='records'),
}
with open(f'{OUT}/per_category_report.json', 'w') as f:
    json.dump(report, f, indent=2, default=str)
print(f'\nWrote {OUT}/per_category_report.json')


=== Hardest categories by worst-case recall ===
                category   n       best_model  best_recall     worst_model  worst_recall  spread
       possible_deadlock   9              VAE          1.0 IsolationForest         0.333   0.667
                     BUG  33  IsolationForest          1.0        PyOD-KNN         0.879   0.121
                   KASAN 445              VAE          1.0        PyOD-KNN         0.944   0.056
                 WARNING 422 PyOD-AutoEncoder          1.0        PyOD-KNN         0.986   0.014
general_protection_fault 341              VAE          1.0 IsolationForest         0.997   0.003
             memory_leak 241  IsolationForest          1.0 IsolationForest         1.000   0.000
                   KMSAN  65  IsolationForest          1.0 IsolationForest         1.000   0.000
                    INFO  53  IsolationForest          1.0 IsolationForest         1.000   0.000
              kernel_BUG  19  IsolationForest          1.0 IsolationForest     

### Reading the breakdown

- **Heatmap (top panel):** each cell = recall on attack rows whose syzbot
  `bug_name` starts with the row category, using the val-tuned threshold.
  Red cells = model lets attacks through.
- **Heatmap (bottom panel):** false-positive rate on the Normal slice — a
  separate scale because there's no "category" for normals; values >5 % flag
  noisy false alarms.
- **Violins:** how much a model's anomaly score separates each category from
  Normal.  A category whose violin overlaps the red threshold line is the one
  the model is bleeding recall on.

If you see one bug category systematically below others, the candidates for
fixing are: (a) add category-specific features; (b) increase weight of
networking / process-creation syscalls (which the EDA flagged as
attack-discriminative); (c) lower threshold for that category at deployment.


## 12. Key Takeaways

### Feature Engineering Impact

| Feature set | IF AUC | VAE AUC |
|---|---|---|
| 78-dim (baseline: top-50 freq + metadata + ver) | 0.979 (mixed training) | 1.000 (overfit on small test) |
| **174-dim (FE: freq_60 + disc_40 + stats_8 + bigram_40 + ver)** | **0.882 (normal-only)** | **0.944** |

The 78-dim results were artificially inflated: IF was trained on mixed data (normal+attack) and
the VAE's perfect score reflected the small, non-representative 5K-doc sample used for
top-ID discovery. The 174-dim pipeline corrects both issues.

### Model Observations

- **IF** improves dramatically when trained on normal-only data (0.56 → 0.88 AUC)
- **VAE** achieves 0.944 AUC with very high recall (≥99%) — catches nearly all attacks
- **Ensemble** is marginal here because VAE already dominates; ensemble weights (α=0.7) were
  calibrated for cases where both models contribute equally
- **Dominant features**: `stat_log_size`, `stat_entropy`, `freq_execve`, `disc_execve` —
  attack sequences trigger `execve` far more often than normal test workloads

### Comparison with DeSFAM Paper

| Metric | DeSFAM (reported) | This Notebook |
|---|---|---|
| Method | Ensemble (α=0.7) | Same |
| Feature source | eBPF live capture | DongTing MongoDB BSON |
| VAE AUC | ~0.95 | 0.944 |
| Precision | 94% | 91.5% |
| Recall | 90% | 99.4% |
