apiVersion: v1
kind: Service
metadata:
  name: tetragon-grpc-nodeport
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: tetragon
  ports:
    - name: grpc
      protocol: TCP
      port: 54321
      targetPort: 54321
      nodePort: 30321
