# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tetragon import events_pb2 as tetragon_dot_events__pb2
from tetragon import sensors_pb2 as tetragon_dot_sensors__pb2
from tetragon import tetragon_pb2 as tetragon_dot_tetragon__pb2


class FineGuidanceSensorsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEvents = channel.unary_stream(
                '/tetragon.FineGuidanceSensors/GetEvents',
                request_serializer=tetragon_dot_events__pb2.GetEventsRequest.SerializeToString,
                response_deserializer=tetragon_dot_events__pb2.GetEventsResponse.FromString,
                )
        self.GetHealth = channel.unary_unary(
                '/tetragon.FineGuidanceSensors/GetHealth',
                request_serializer=tetragon_dot_tetragon__pb2.GetHealthStatusRequest.SerializeToString,
                response_deserializer=tetragon_dot_tetragon__pb2.GetHealthStatusResponse.FromString,
                )
        self.AddTracingPolicy = channel.unary_unary(
                '/tetragon.FineGuidanceSensors/AddTracingPolicy',
                request_serializer=tetragon_dot_sensors__pb2.AddTracingPolicyRequest.SerializeToString,
                response_deserializer=tetragon_dot_sensors__pb2.AddTracingPolicyResponse.FromString,
                )
        self.DeleteTracingPolicy = channel.unary_unary(
                '/tetragon.FineGuidanceSensors/DeleteTracingPolicy',
                request_serializer=tetragon_dot_sensors__pb2.DeleteTracingPolicyRequest.SerializeToString,
                response_deserializer=tetragon_dot_sensors__pb2.DeleteTracingPolicyResponse.FromString,
                )
        self.ListTracingPolicies = channel.unary_unary(
                '/tetragon.FineGuidanceSensors/ListTracingPolicies',
                request_serializer=tetragon_dot_sensors__pb2.ListTracingPoliciesRequest.SerializeToString,
                response_deserializer=tetragon_dot_sensors__pb2.ListTracingPoliciesResponse.FromString,
                )
        self.ConfigureTracingPolicy = channel.unary_unary(
                '/tetragon.FineGuidanceSensors/ConfigureTracingPolicy',
                request_serializer=tetragon_dot_sensors__pb2.ConfigureTracingPolicyRequest.SerializeToString,
                response_deserializer=tetragon_dot_sensors__pb2.ConfigureTracingPolicyResponse.FromString,
                )
        self.EnableTracingPolicy = channel.unary_unary(
                '/tetragon.FineGuidanceSensors/EnableTracingPolicy',
                request_serializer=tetragon_dot_sensors__pb2.EnableTracingPolicyRequest.SerializeToString,
                response_deserializer=tetragon_dot_sensors__pb2.EnableTracingPolicyResponse.FromString,
                )
        self.DisableTracingPolicy = channel.unary_unary(
                '/tetragon.FineGuidanceSensors/DisableTracingPolicy',
                request_serializer=tetragon_dot_sensors__pb2.DisableTracingPolicyRequest.SerializeToString,
                response_deserializer=tetragon_dot_sensors__pb2.DisableTracingPolicyResponse.FromString,
                )
        self.ListSensors = channel.unary_unary(
                '/tetragon.FineGuidanceSensors/ListSensors',
                request_serializer=tetragon_dot_sensors__pb2.ListSensorsRequest.SerializeToString,
                response_deserializer=tetragon_dot_sensors__pb2.ListSensorsResponse.FromString,
                )
        self.EnableSensor = channel.unary_unary(
                '/tetragon.FineGuidanceSensors/EnableSensor',
                request_serializer=tetragon_dot_sensors__pb2.EnableSensorRequest.SerializeToString,
                response_deserializer=tetragon_dot_sensors__pb2.EnableSensorResponse.FromString,
                )
        self.DisableSensor = channel.unary_unary(
                '/tetragon.FineGuidanceSensors/DisableSensor',
                request_serializer=tetragon_dot_sensors__pb2.DisableSensorRequest.SerializeToString,
                response_deserializer=tetragon_dot_sensors__pb2.DisableSensorResponse.FromString,
                )
        self.RemoveSensor = channel.unary_unary(
                '/tetragon.FineGuidanceSensors/RemoveSensor',
                request_serializer=tetragon_dot_sensors__pb2.RemoveSensorRequest.SerializeToString,
                response_deserializer=tetragon_dot_sensors__pb2.RemoveSensorResponse.FromString,
                )
        self.GetStackTraceTree = channel.unary_unary(
                '/tetragon.FineGuidanceSensors/GetStackTraceTree',
                request_serializer=tetragon_dot_sensors__pb2.GetStackTraceTreeRequest.SerializeToString,
                response_deserializer=tetragon_dot_sensors__pb2.GetStackTraceTreeResponse.FromString,
                )
        self.GetVersion = channel.unary_unary(
                '/tetragon.FineGuidanceSensors/GetVersion',
                request_serializer=tetragon_dot_sensors__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=tetragon_dot_sensors__pb2.GetVersionResponse.FromString,
                )
        self.RuntimeHook = channel.unary_unary(
                '/tetragon.FineGuidanceSensors/RuntimeHook',
                request_serializer=tetragon_dot_tetragon__pb2.RuntimeHookRequest.SerializeToString,
                response_deserializer=tetragon_dot_tetragon__pb2.RuntimeHookResponse.FromString,
                )
        self.GetDebug = channel.unary_unary(
                '/tetragon.FineGuidanceSensors/GetDebug',
                request_serializer=tetragon_dot_sensors__pb2.GetDebugRequest.SerializeToString,
                response_deserializer=tetragon_dot_sensors__pb2.GetDebugResponse.FromString,
                )
        self.SetDebug = channel.unary_unary(
                '/tetragon.FineGuidanceSensors/SetDebug',
                request_serializer=tetragon_dot_sensors__pb2.SetDebugRequest.SerializeToString,
                response_deserializer=tetragon_dot_sensors__pb2.SetDebugResponse.FromString,
                )


class FineGuidanceSensorsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTracingPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTracingPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTracingPolicies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureTracingPolicy(self, request, context):
        """ConfigureTracingPolicy can be used to configure a loaded tracing policy.
        It can be used to:
        - enable/disable it
        - change its mode (enforcement vs monitoring)
        If multiple changes are requested and an error is encountered, the resulting state might have
        partial updates applied. In other words, the configuring a tracing policy is not atomic.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableTracingPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableTracingPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSensors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableSensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableSensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveSensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStackTraceTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RuntimeHook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDebug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDebug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FineGuidanceSensorsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.GetEvents,
                    request_deserializer=tetragon_dot_events__pb2.GetEventsRequest.FromString,
                    response_serializer=tetragon_dot_events__pb2.GetEventsResponse.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=tetragon_dot_tetragon__pb2.GetHealthStatusRequest.FromString,
                    response_serializer=tetragon_dot_tetragon__pb2.GetHealthStatusResponse.SerializeToString,
            ),
            'AddTracingPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTracingPolicy,
                    request_deserializer=tetragon_dot_sensors__pb2.AddTracingPolicyRequest.FromString,
                    response_serializer=tetragon_dot_sensors__pb2.AddTracingPolicyResponse.SerializeToString,
            ),
            'DeleteTracingPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTracingPolicy,
                    request_deserializer=tetragon_dot_sensors__pb2.DeleteTracingPolicyRequest.FromString,
                    response_serializer=tetragon_dot_sensors__pb2.DeleteTracingPolicyResponse.SerializeToString,
            ),
            'ListTracingPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTracingPolicies,
                    request_deserializer=tetragon_dot_sensors__pb2.ListTracingPoliciesRequest.FromString,
                    response_serializer=tetragon_dot_sensors__pb2.ListTracingPoliciesResponse.SerializeToString,
            ),
            'ConfigureTracingPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureTracingPolicy,
                    request_deserializer=tetragon_dot_sensors__pb2.ConfigureTracingPolicyRequest.FromString,
                    response_serializer=tetragon_dot_sensors__pb2.ConfigureTracingPolicyResponse.SerializeToString,
            ),
            'EnableTracingPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableTracingPolicy,
                    request_deserializer=tetragon_dot_sensors__pb2.EnableTracingPolicyRequest.FromString,
                    response_serializer=tetragon_dot_sensors__pb2.EnableTracingPolicyResponse.SerializeToString,
            ),
            'DisableTracingPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableTracingPolicy,
                    request_deserializer=tetragon_dot_sensors__pb2.DisableTracingPolicyRequest.FromString,
                    response_serializer=tetragon_dot_sensors__pb2.DisableTracingPolicyResponse.SerializeToString,
            ),
            'ListSensors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSensors,
                    request_deserializer=tetragon_dot_sensors__pb2.ListSensorsRequest.FromString,
                    response_serializer=tetragon_dot_sensors__pb2.ListSensorsResponse.SerializeToString,
            ),
            'EnableSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableSensor,
                    request_deserializer=tetragon_dot_sensors__pb2.EnableSensorRequest.FromString,
                    response_serializer=tetragon_dot_sensors__pb2.EnableSensorResponse.SerializeToString,
            ),
            'DisableSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableSensor,
                    request_deserializer=tetragon_dot_sensors__pb2.DisableSensorRequest.FromString,
                    response_serializer=tetragon_dot_sensors__pb2.DisableSensorResponse.SerializeToString,
            ),
            'RemoveSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveSensor,
                    request_deserializer=tetragon_dot_sensors__pb2.RemoveSensorRequest.FromString,
                    response_serializer=tetragon_dot_sensors__pb2.RemoveSensorResponse.SerializeToString,
            ),
            'GetStackTraceTree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStackTraceTree,
                    request_deserializer=tetragon_dot_sensors__pb2.GetStackTraceTreeRequest.FromString,
                    response_serializer=tetragon_dot_sensors__pb2.GetStackTraceTreeResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=tetragon_dot_sensors__pb2.GetVersionRequest.FromString,
                    response_serializer=tetragon_dot_sensors__pb2.GetVersionResponse.SerializeToString,
            ),
            'RuntimeHook': grpc.unary_unary_rpc_method_handler(
                    servicer.RuntimeHook,
                    request_deserializer=tetragon_dot_tetragon__pb2.RuntimeHookRequest.FromString,
                    response_serializer=tetragon_dot_tetragon__pb2.RuntimeHookResponse.SerializeToString,
            ),
            'GetDebug': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDebug,
                    request_deserializer=tetragon_dot_sensors__pb2.GetDebugRequest.FromString,
                    response_serializer=tetragon_dot_sensors__pb2.GetDebugResponse.SerializeToString,
            ),
            'SetDebug': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDebug,
                    request_deserializer=tetragon_dot_sensors__pb2.SetDebugRequest.FromString,
                    response_serializer=tetragon_dot_sensors__pb2.SetDebugResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tetragon.FineGuidanceSensors', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FineGuidanceSensors(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/tetragon.FineGuidanceSensors/GetEvents',
            tetragon_dot_events__pb2.GetEventsRequest.SerializeToString,
            tetragon_dot_events__pb2.GetEventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tetragon.FineGuidanceSensors/GetHealth',
            tetragon_dot_tetragon__pb2.GetHealthStatusRequest.SerializeToString,
            tetragon_dot_tetragon__pb2.GetHealthStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddTracingPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tetragon.FineGuidanceSensors/AddTracingPolicy',
            tetragon_dot_sensors__pb2.AddTracingPolicyRequest.SerializeToString,
            tetragon_dot_sensors__pb2.AddTracingPolicyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTracingPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tetragon.FineGuidanceSensors/DeleteTracingPolicy',
            tetragon_dot_sensors__pb2.DeleteTracingPolicyRequest.SerializeToString,
            tetragon_dot_sensors__pb2.DeleteTracingPolicyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTracingPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tetragon.FineGuidanceSensors/ListTracingPolicies',
            tetragon_dot_sensors__pb2.ListTracingPoliciesRequest.SerializeToString,
            tetragon_dot_sensors__pb2.ListTracingPoliciesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfigureTracingPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tetragon.FineGuidanceSensors/ConfigureTracingPolicy',
            tetragon_dot_sensors__pb2.ConfigureTracingPolicyRequest.SerializeToString,
            tetragon_dot_sensors__pb2.ConfigureTracingPolicyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnableTracingPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tetragon.FineGuidanceSensors/EnableTracingPolicy',
            tetragon_dot_sensors__pb2.EnableTracingPolicyRequest.SerializeToString,
            tetragon_dot_sensors__pb2.EnableTracingPolicyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisableTracingPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tetragon.FineGuidanceSensors/DisableTracingPolicy',
            tetragon_dot_sensors__pb2.DisableTracingPolicyRequest.SerializeToString,
            tetragon_dot_sensors__pb2.DisableTracingPolicyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tetragon.FineGuidanceSensors/ListSensors',
            tetragon_dot_sensors__pb2.ListSensorsRequest.SerializeToString,
            tetragon_dot_sensors__pb2.ListSensorsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnableSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tetragon.FineGuidanceSensors/EnableSensor',
            tetragon_dot_sensors__pb2.EnableSensorRequest.SerializeToString,
            tetragon_dot_sensors__pb2.EnableSensorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisableSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tetragon.FineGuidanceSensors/DisableSensor',
            tetragon_dot_sensors__pb2.DisableSensorRequest.SerializeToString,
            tetragon_dot_sensors__pb2.DisableSensorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tetragon.FineGuidanceSensors/RemoveSensor',
            tetragon_dot_sensors__pb2.RemoveSensorRequest.SerializeToString,
            tetragon_dot_sensors__pb2.RemoveSensorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStackTraceTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tetragon.FineGuidanceSensors/GetStackTraceTree',
            tetragon_dot_sensors__pb2.GetStackTraceTreeRequest.SerializeToString,
            tetragon_dot_sensors__pb2.GetStackTraceTreeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tetragon.FineGuidanceSensors/GetVersion',
            tetragon_dot_sensors__pb2.GetVersionRequest.SerializeToString,
            tetragon_dot_sensors__pb2.GetVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RuntimeHook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tetragon.FineGuidanceSensors/RuntimeHook',
            tetragon_dot_tetragon__pb2.RuntimeHookRequest.SerializeToString,
            tetragon_dot_tetragon__pb2.RuntimeHookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDebug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tetragon.FineGuidanceSensors/GetDebug',
            tetragon_dot_sensors__pb2.GetDebugRequest.SerializeToString,
            tetragon_dot_sensors__pb2.GetDebugResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDebug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tetragon.FineGuidanceSensors/SetDebug',
            tetragon_dot_sensors__pb2.SetDebugRequest.SerializeToString,
            tetragon_dot_sensors__pb2.SetDebugResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
